### ISSUE TITLE
comparison to (re)actors ??

### ISSUE THREAD

**Issue by jokeyrhyme** [yelouafi/redux-saga#141]
I'm trying to decide whether my project should use sagas or (re)actors (or both), and besides the documentation for this project I have also read:

- http://jamesknelson.com/join-the-dark-side-of-the-flux-responding-to-actions-with-actors/

- https://medium.com/@mtiller/encapsulating-application-logic-with-reactors-392635763e7

> Actors are a sequence of functions which are called each time your store’s state changes, with one important exception: they aren’t called in response to actions dispatched from other actors.

This isn't really a property of actors, but of the suggested approach of hooking them up to the store:

```js
// An array of actor functions taking a `state` object and `dispatch` function
var actors = [ ... ]

var acting = false
store.subscribe(function() {
  // Ensure that any action dispatched by actors do not result in a new
  // actor run, allowing actors to dispatch with impunity.
  if (!acting) {
    acting = true
    actors.forEach(function() {
      actor(store.getState(), store.dispatch)
    })
    acting = false
  }
})
```

They even go so far as to implement the connection between React and Redux as the final actor in the sequence, so that React render calls for intermediate synchronous states are avoided.

It seems as though both saga and actor approaches offer comparable side-effect management. 

- is the actor approach better approach for synchronous side-effects in terms of React efficiency?

- is the saga approach better for asynchronous side-effects in terms of declaration and testing?

- is it likely that a project would ever benefit from using both? or do most use cases fit cleanly into either one or the other approach?

**Comment by jokeyrhyme** [comment]
One of the stated benefits of the actor approach is that becomes simple to redirect a navigation internally without the user seeing any intermediate states.

**Comment by zalmoxisus** [comment]
I think having intermediate states in the history is better as we can debug why and from where the user got redirected. If If you don't have to wait any async response before changing the state, the user will not get any intermediate states and React will render only the last one. You can find an example [here](https://github.com/zalmoxisus/social-expert/blob/master/src/app/sagas/auth.js#L25-L30).

**Comment by slorber** [comment]
@jokeyrhyme a [Saga](https://msdn.microsoft.com/en-us/library/jj591569.aspx) is a pattern that is often used in EventSourcing/CQRS/DDD. It can be implemented in different ways.

In some functional languages like Erlang or Scala (which use extensively the actor model) the saga pattern is often [implemented on top of actors](https://github.com/pawelkaczor/ddd-leaven-akka/blob/master/src/main/scala/ddd/support/domain/Saga.scala)

redux-saga is kind of similar to actors except it does not implement a lot of unneeded features like parent/child sender/receiver communication, or retry/recovery patterns. Remember that the actor pattern was initially built with Erlang with failure handling in mind, for reliability of telco networks. Another difference is its focus on testability by using an interpreter for yielded effects, also permitting to get a better idea of what is happening in the long run (which is more complicated to achieve in distributed systems implemented with actors, requiring tools like [Zipkin](https://github.com/openzipkin/zipkin))

**Comment by yelouafi** [comment]
@slorber From the 1st link I think the author gives a different meaning to actors than the one commonly known in the Actor model.

@jokeyrhyme 
Actors in the Actor model communicates by sending messages to each other while in the above link the author talks about reacting to state changes. In the mentioned article, actors are functions invoked on each state change, can dispatch actions and forms a kind of a pipeline where each actor can see the results of actions dispatched by previous actors on the chain.

I can see 2 principal concerns from my rapid lecture

1. ability to dispatch actions in reactions to other actions
2. amelioration of performance rendering by not rendering on each state change

The 2nd concern seems more technical than conceptual and IMO can be handled by different means (like using [redux-batched-actions](https://github.com/tshelburne/redux-batched-actions)).

The 1st concern joins somewhat the Saga purpose, as Sagas can also translate user events into business events that maybe handled by other Sagas. And those Sagas can in turn generate other events to be used by other Sagas.

I don't see why the author chose to deliberately ignore actions and just examines just state changes in order to infer the next action or effect. It means the developer will likely store more control state in the store in order to give re-actors enough information to decide what to do.

**Comment by jokeyrhyme** [comment]
Thanks everyone, that's given me a lot to think about. :)
