### ISSUE TITLE
Support channels

### ISSUE THREAD

**Issue by kloy** [yelouafi/redux-saga#155]
It would be great if channels could be yielded as an alternative to utilizing promises and node style callbacks. In general I would prefer to utilize generators for all async behavior to avoid common pitfalls with promises and callbacks. Channels also the obvious benefit of handling multiple updates and supporting functional mutation out of box.

**Comment by yelouafi** [comment]
First, I'm glad you opened this issue

In the csp branch you'll find I'm already experiencing with this

Code

https://github.com/yelouafi/redux-saga/blob/csp/src/internal/channel.js

Test

https://github.com/yelouafi/redux-saga/blob/csp/test/channels/channel.js

redux-saga is not quite csp. the take model is more close to eventEmitter (or hot observables in Rx) because it doesn't buffer events (principally for technical reasons)

My goal is not to add a feature for itself. Until now I tried to adopt a pragmatic approach, I only add features needed by the users (cancellation, select). Actually what I think the lib lacks is some way to connect to external event sources (websockets, obervables ...) I'm more willing for an event iterator concept : An iterator that connects to the event source and buffer events in order for sagas to take them. It means Sagas will not miss those events even if they were blocked while those events happened: i.e. they will be processed in order. It's like a half of csp channels (just the take side of a channel). 

CSP channels adds support for synchronous puts: A saga can 'put'  a message for another/others saga(s), and the put will block until one Saga takes that message, The model can handle inter-process communication and synchronisation using the famous rendez-vous mechanism, but I'm not sure if this use case is really needed by redux/saga users, plus it's not easy to grok by people (especially with buffered channels: dropping, sliding ...). I don't want to provide some complicated feature that no one or only few persons will use.

I'm also exploring some similar ideas like the [linda programming model](https://en.wikipedia.org/wiki/Linda_(coordination_language)). Which is similar to csp but uses fewer semantics (a global channel called the tuple space). You can find some of my experiments here

https://github.com/yelouafi/linda/blob/master/examples/gen/hello.js

I don't plan to add this model to redux-saga. Just trying to find some inspiration

**Comment by kloy** [comment]
Thank you for the detailed explanation. 

I could see you getting the same issue opened for Rx, bacon, etc. What may be a better solution is to provide a facility for decorating `call`. Alternatively, I like the idea of actually implementing a pure eventEmitter since adapters already exist for many observable implementations. If you consider the approach of calling Promises or node style callbacks, the current philosophy seems to be one of interoperability with popular async strategies. With that said, I am very interested to see what you come up with as an alternative observable mechanism.

If I rephrased the issue to not be channel specific I think it may go something like...

"I would like to use my observable based framework that my code base already depends on with sagas".

**Comment by axelson** [comment]
We have a use-case for this as well since we're using websockets (via pusher.js). We thought about using the deferred pattern found in #51 but it is more code than we feel is necessary and we're worried that we might drop events.

**Comment by yelouafi** [comment]
see API proposal #254
