### ISSUE TITLE
Significant lag in dispatching?

### ISSUE THREAD

**Issue by joshwcomeau** [yelouafi/redux-saga#159]
I'm a newcomer to Redux Saga, and am trying to use it in a performance-sensitive application.

My setup is super simple, adapted from the intro tutorial.

In my React component, I bind an event on click to dispatch the following action:

```js
export function selectArtist(artist) {
  console.log("Select Artist called in action", performance.now())
  return {
    type: SELECT_ARTIST,
    artist
  }
}
```

The action is responded to with this saga:

```js
export function* selectArtist(action) {
  yield put(markArtistAsSelected(action.node));
}

export function* watchSelectArtist() {
  yield* takeEvery(SELECT_ARTIST, selectArtist)
}
```

The reducer handles the action `put` by the saga:

```js
export default function reducer(state = fromJS(nodesData), action) {
  switch (action.type) {
    case MARK_ARTIST_AS_SELECTED:
      console.log("Reducer hit!", performance.now());
      // other stuff
  }
}
```

My problem is with the performance of this implementation. You can see I added some logs with `performance.now()` to benchmark. This implementation takes ~60-90ms to get from the action to the reducer.

Comparatively, using Redux Thunk takes 1-2ms.

Am I doing something wrong, or is this just the inherent cost of using generators? In most applications, 60ms might not be too bad but it's noticeable for what I'm doing.

I really like the API and methodology of redux saga :) I'm really hoping there's a way to get that timing down!

Full source here: https://github.com/joshwcomeau/panther

**Comment by slorber** [comment]
There are 2 possible cases here:
- The saga is slow and takes 90ms to dispatch the new action
- The saga is delayed for something like 90ms for unknown reasons 

The saga code is called AFTER your store's root reducer is called and has computed the new state.

I suspect that your reducer is slow, and that the saga is delayed by 90ms because it is the time your reducer takes to handle that event.


You should try to log performance around these updates:

```javascript
return state.updateIn([FUTURE, 'nodes'], nodes => {
        return nodes.map( (node, index) => {
          return nodeIndex === index
          ? node.set( 'selected', true )
          : node.set( 'rejected', true );
        });
      });
```

I may be wrong but it is likely to me that this part of your app is slower than you think and takes 90ms. 
I use redux-saga and did not notice any performance problem with it.

If that's not the case don't hesitate to show the former redux-thunk version (including log statements).

**Comment by joshwcomeau** [comment]
@slorber I did the following:

```js
      console.log("Start new state", performance.now())

      const newState = state.updateIn([FUTURE, 'nodes'], nodes => {
        return nodes.map( (node, index) => {
          return nodeIndex === index
          ? node.set( 'selected', true )
          : node.set( 'rejected', true );
        });
      });

      console.log("Finish new state", performance.now())

      return newState
```

And got the following:

```
Start new state 5387.865000000001
Finish new state 5388.795
```

So yeah, that part takes less than 1 millisecond. It isn't the problem.

I did notice, when putting more logs in the reducer, that there is a lot of stuff happening and I'm not sure why:

![screen shot 2016-02-29 at 9 25 59 am](https://cloud.githubusercontent.com/assets/6692932/13397124/813ed86c-dec6-11e5-9da2-292aa87ca1ff.png)

This looks wrong for so many reasons. Things are being resolved before being triggered.

Here's what the redux thunk version looks like:

![screen shot 2016-02-29 at 9 29 20 am](https://cloud.githubusercontent.com/assets/6692932/13397203/f1eb3452-dec6-11e5-86bf-01ac233ae77e.png)

At a loss as to what could be wrong, I followed the intro tutorial pretty closely.. Appreciate any light anyone can shed!

**Comment by slorber** [comment]
Can you log the execution time of each action inside the reducer? Because here we only see the time when the reducer receives the action, but it does not show how much time does this action takes to be handled.


Also it would help if you log the time around each dispatch.


Also do you use a saga monitor? Can you try without it?

Can you also try to use actionCreators/thunks without disabling the saga middleware?

**Comment by joshwcomeau** [comment]
Not sure what you mean by the execution time of the action inside the reducer, I believe I am doing that. I start the "clock" before the state mutation, and end it right before returning the new state. I believe if the reducer's operations was the problem, it would be consistently slow between Redux Saga and the Thunk alternative. I could be mistaken though.

I am not using a saga monitor.

I'm at work now so I can't edit it right now, but I will post what you've asked for this evening :) Thanks for your help!

The other thing I'm unclear about is if that sequence of events in the reducer is correct. Is there a bug in my saga code? Why are 3 effects being triggered, and why are they resolved before being triggered?

**Comment by slorber** [comment]
@joshwcomeau as far as I know redux-saga do dispatch internal events so that we could plug additional devtools based on these (like the saga monitor I mention).

It seems that each of these events are 15ms from each others, so there is something weird that takes time because if you don't have a saga monitor nobody else should be interested by these events...
Maybe try to use redux-ignore so that these events never gets dispatched to your reducer?

**Comment by yelouafi** [comment]
@joshwcomeau `put` effects are dispatched on the next microtask (Promise.then) but 60-90ms is too high for the Promise.then latency even with a polyfilled version.

I think there is time lost in dispatching Saga monitor events (monitor events are only dispatched in the development mode) : Each time a Saga yield an effect, a monitoring event is dispatched and will go throw the entire store.dispatch pipeline (unless intercepted by the Saga monitor). So you may try to disable dev. mode to see the impact.

I did some quick experiments on the counter demo (sceenshots below), the 1st in dev mode (monitoring enabled) and the 2nd with monitoring disabled. You can see the diff between the 2 effects

With monitoring enabled

![log-saga-perf](https://cloud.githubusercontent.com/assets/5453835/13404140/39bece30-df10-11e5-93f0-9bb1f263c4a8.png)

With monitoring disabled

![log-saga-perf-prod](https://cloud.githubusercontent.com/assets/5453835/13404150/418a6b38-df10-11e5-9426-c05f432d3376.png)


As for the Effect-triggred/resolved order; i think the first Effect resolved action belongs to a formed effect, you can verify by logging the whole Effect action (like above) so you can see the actual effectIds in the sequence

**Comment by joshwcomeau** [comment]
@slorber Thanks for the tip about redux-ignore!

@yelouafi thanks so much for spending the time experimenting with this :) am I correct in assuming that development mode is disabled the same way as in production? By setting `process.env.NODE_ENV`?

Will post an update later when I've had the chance to experiment with dev/prod mode.

**Comment by joshwcomeau** [comment]
Success! Switching to production mode lowers it to just 11ms :D

So glad I get to keep using redux saga. Thanks again @slorber and @yelouafi!

![screen shot 2016-02-29 at 8 42 51 pm](https://cloud.githubusercontent.com/assets/6692932/13414992/16acd59e-df25-11e5-9200-32eaba7bdab9.png)

**Comment by slorber** [comment]
great!

@yelouafi how comes this dev mode is so expensive?

**Comment by yelouafi** [comment]
```javascript
while(true) {
  yield take(ACTION)
  yield fork(worker)
}
```

when `ACTION` is dispatched there will be an `EFFECT_RESOLVED` for the `take` effect, then a pair `EFFECT_TRIGGERED/RESOLVED` for the fork effect. Each event will be dispatched in a microstask and will also trigger a full Store.dispatch cycle. If there is no Saga monitor to intercept events, then the actions will also be invoked on the entire reducer tree

I think it's the accumulated effect of both monitor events dispatching and the overhead of microtasks

**Comment by slorber** [comment]
makes sense but what I see in source code is that the reudcer tree of @joshwcomeau is pretty small and will ignore fastly all these redux-saga events. The overhead of microtasks is unlikely to delay each dispatchs of 15ms.

Maybe there's an existing middleware that does not handle redux-saga effects in an efficient way. I suggest some middleware is trying to log the effect actions, and in some cases it may not be performant because you put tasks in these effects. I think redux-saga should rather avoid to dispatch unserializable events containing objects with methods, like promises or errors. And it may be the cause of this latency no?

**Comment by yelouafi** [comment]
Maybe. I'll have to check that

**Comment by eric-burel** [comment]
Hi,
This should not be closed, as it is not solved: switching to prod isn't a solution, I may not want my saga to lag on dev too.
There should be some way to disable those debug events by configuring redux-saga (or some doc about it, I may have missed something :) ).

**Comment by Andarist** [comment]
@eric-burel please share ur sample repository with issue reproduced. The issue mentioned in this thread no longer exists (or at least the underlaying reason might be different) because `redux-saga` is no longer dispatching any debug events - instead it allows you to pass in `sagaMonitor` object if you want debug this way, but it is an opt-in and doesnt do anything if not passed explicitly.

**Comment by eric-burel** [comment]
Okay, actually redux-logger seemed to be the responsible of lag issues in my case, it was the first I investigated and it succeed, saga does not seem to create much troubles. Thanks for the very quick answer!

**Comment by csvan** [comment]
Is there any way to put redux-saga into production mode _without_ fiddling with NODE_ENV? E.g. if I want to run React in dev mode but redux-saga in prod mode?

**Comment by Andarist** [comment]
@csvan you always can patch-package Redux Saga. I wonder though what's causing the slowness - could you share a performance profile or something?

**Comment by csvan** [comment]
@Andarist after careful digging it turned out our profile was misleading and that the problem was in another package. Thanks for the help anyway 😊
