### ISSUE TITLE
Improve error reporting and logging

### ISSUE THREAD

**Issue by pke** [yelouafi/redux-saga#168]
I had wrong imports of functions and wanted to use them in `take(invalidMethod)` and all I got was a mysterious invalid type error in the console. I did not know which saga it originated from.
I understand that redux-saga cannot know where it comes from.

Therefore I am thinking maybe we can extend the saga steps with optional comments, that will help to improve error reporting.

```
yield log(take(WAIT_FOR_ACTION), "Waiting for action")
yield log(call(asyncFunc, withParams), "Calling async function")
yield log(put(SET_RESULT_ACTION), "Setting the result of the async call")
```

It would not break the existing API
What you think?

Proposed implementation:

```
function *log(func, message) {
  console.log(message)
  yield func
}
```

**Comment by slorber** [comment]
it looks like a great idea to me to be able to attach a log or context to each executed effect.
The saga monitor tools could be able to display these messages as well so that it's easier to understand what is happening.

I don't agree with the proposed implementation, as if the log is not an effect and not processed by the generator it only logs to the console and is unusable with saga devtools.

It would somehow be similar to the writer monad for generators.

**Comment by pke** [comment]
What implementation do you suggest, @slorber?
I have to check out the saga monitor tools still. But this form of simple logging helped me a lot to find flaws in my sagas.

Also since "function*" are just function we could attach the log info to them also directly:

```
function log(func, message) {
  console.log(func.name + ": " + message)
  func.log = message
  return func
}
```

That way an effects inspector could read out the message. Would that work?

**Comment by slorber** [comment]
@pke I'm not saying it's not helpful to log like that, it's just that it just logs to the console and we could do better IMO, but this logging thing should probably be implemented inside the processor of redux-saga.

there used to be a method `window.$$logSagaTrace()` but I can't find it back. It may have helped you to find the source of your problem. @yelouafi any idea why this method is not available anymore in latest versions?

**Comment by pke** [comment]
Sure I am all for better tooling. In my case the logging is done inside an app, and on the mobile device you cannot really open dev tools. So I log all those things to a file, that the user can (even in prod mode) send us the file and we can see what went on.

But a universal hook into the saga processing would be great to have.

**Comment by bolismauro** [comment]
I'm not sure if this is related to this issue but I've just started to work with sagas and I find almost impossible to debug saga code. The main issues I have are:
- breakpoints basically don't work (either they are not triggered, or functions like 'next step' behave in a weird way
- when there is an exception inside a saga (or a function invoked using `call` inside a saga) nor the stack trace or the error message is meaningful

I'm using the latest version of Chrome but I've also tried Safari and Chrome.
Most likely these issues are not directly related to redux-saga but I wonder if there is a way to support developers in the debugging process because right now I think it is really really hard

**Comment by yelouafi** [comment]
@pke I think you can implement the `log` utility without involving the core. `put`, `take`, ... are simple pure functions which return plain objects so you can just wrap them in whatever you want

```javascript
function log(effect, message) {
  console.log(message)
  return effect
}

function* saga() {
  // will log then return the result of take
  yield log(take(WAIT_FOR_ACTION), "Waiting for action")
}
```

**Comment by yelouafi** [comment]
@slorber it's `$$LogSagas()` now

**Comment by slorber** [comment]
thanks :)
