### ISSUE TITLE
Compatibility with redux-electron-store?

### ISSUE THREAD

**Issue by fasterthanlime** [yelouafi/redux-saga#181]
So, I'm trying to make redux-saga play nice with [redux-electron-store](https://github.com/samiskin/redux-electron-store), and I'm not having much success.

It comes down to the composition order. As far as I can tell, if I do:

```javascript
// (imports, creating saga middleware, etc.)

const enhancer = compose(
  applyMiddleware(sagaMiddleware),
  electronEnhancer()
)
```

...then, actions dispatched from the renderer, received by the browser via IPC, aren't received by saga at all (they're never seen by 'take', seemingly because they don't even go through naga middleware)

On the other hand, if I do:

```javascript
// (imports, creating saga middleware, etc.)

const enhancer = compose(
  electronEnhancer()
  applyMiddleware(sagaMiddleware),
)
```

...then saga does see actions dispatched from the renderer, *but* saga `put` effects never make their way to the electron enhancer, so they're never sent to the renderer itself.

Looks like a bit of a catch-22 - I've considered turning redux-saga into a store enhancer, or turning redux-electron-store into a middleware.. neither of which I'm sure would help.

Or maybe saga could (optionally) be split into two middlewares? one for take, one for put? Honestly at this point, I'm fine with maintaining my fork if that's what it takes, I'd understand @yelouafi not wanting to add redux-electron-store specific workarounds directly in redux-saga.

(/cc @samiskin from redux-electron-store, any and all pointers are greatly appreciated..)

**Comment by fasterthanlime** [comment]
Nevermind, I fixed it in my fork: https://github.com/fasterthanlime/redux-electron-enhancer

**Comment by yelouafi** [comment]
Perhaps the `runSaga` helper would help

http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagaiterator-subscribe-dispatch-getstate-monitor

Here is an example on how to connect to an already created store

https://github.com/yelouafi/redux-saga/blob/master/src/internal/runSaga.js#L16-L38

But the downside is that you'll only be able to take and put from outside; actions dispatched from inside (by middlewares) won't be seen by sagas. But actions dispatched from outside (components, or manually using store.dispatch) will work with take/put.


>Or maybe saga could (optionally) be split into two middlewares? one for take, one for put?

I think this issue is inherent to how Redux's enhancer composition works. Maybe @gaearon have some advice here.
