### ISSUE TITLE
How to avoid running multiple sagas/requests with the same arguments

### ISSUE THREAD

**Issue by tarjei** [yelouafi/redux-saga#189]
Hi, 

I got a saga that looks something like this:

```js

function * getFromServer(query) {

   var state = yield select(selectQueryState)
   if (state.queryState[query]) {
     return
   }

   yield PUT(queryIsExecuting(query))

   yield doXhttpRequest(query)
   ... handle responses etc

}
```

My question is: How do I avoid multiple queries for the same resource here?

Should I move the pending query state handling outside of the saga and handle that by having the reducer listen to the action triggering the query?

It seems so because I see that the state changes I do within the saga do not happen at the same time (as per this comment: https://github.com/yelouafi/redux-saga/issues/167#issuecomment-192672932)

**Comment by tarjei** [comment]
I also note in the API docs that you write: "A saga should preferably depend only on its own internal control state when possible."

Isn't this a bit against the credo of Redux? I.e. keeping and modifying state outside of the Store. 

It seems to me that the only way to achieve what I want is to maintain a hash of queries that my getFromServer method checks. 

Am I right?

Regards,
Tarjei

**Comment by yelouafi** [comment]
it's not clear from your first question if you need to

1. memoize xhr call results for queries to the same resource *all the time*
2. prevent requests for the same result to run *concurrently* ie you don't want to memoize results for all queries but just for those running concurrently at a given time

>Isn't this a bit against the credo of Redux? I.e. keeping and modifying state outside of the Store.

There is a distinction between 'view state' and 'control state'. The first is meant to be presented (directly or indirectly) to the application user. The second is meant to drive the operations and not meant to be presented to the user.

The question of course is whether we should keep the control state inside the Redux Store or not. Well as usual there are different opinions and pros and cons

If you keep the control state inside the Store then you'll achieve that famous credo 'keep all state inside the Store', your entire control flow can be time-traveled (in theory, I've yet to see that in practice, because time-traveling control flow present some conceptual challenges i.e. keeping the control state in the Store doesn't give you control-flow time-traveling for free).

But now, you'll have to drive all your control flow from inside the reducers, this means you'll have to keep all 'program control variables' in the store to keep track where you're actually on the flow; this is not an issu with simple fire-and-forget ajax requests; but as soon as you get to more serious cases (handling concurrent requeusts, long-running flows like login-logout etc...) the reducer code will become more complicated.

[redux-loop](https://github.com/raisemarketplace/redux-loop) implements a similar concept, the reducer function has a signature (state, action) => (newState, ...Effects) : you return your desired side effects (e.g. ajax call) right from the reducers thus you'll keep all your control state inside the store

redux-saga OTOH implements the 2nd approach, implements the control flow outside of the reducers: thus if you opt for Sagas you already adheres to keeping your control state outside of the store. Suppose you have this Saga

```javascript
function* congratulateAfter3TodosCreation() {
  yield take('CREATE_TODO')
  yield take('CREATE_TODO')
  yield take('CREATE_TODO')
 
  yield put({type: 'SHOW_CONGRATULATION'})
}
```

I know we could've done it with a `for` but I wanted to point to something more subtle, suppose we took 2 `CREATE_TODO` actions and now the Saga is waiting for the 3rd one. The fact the Saga is now at the 3rd `take` statement can be viewed as a control state itself, and this control state is *implicit* (ie implied by the execution sequence that leads to that statement). My point is that using redux-saga you'll forcibly externalize your control state. In fact, that's the purpose of Sagas.

So does that mean you must never use the redux Store to drive the Saga operations ? Well there are pros and cons for this too (as usual). Using the store's state means the Saga will be coupled with state shape (this can be alleviated with `yield select`) but OTOH there are some situations where the view state itself is inveitably needed by the Saga. 

For example, think of a real shopping cart application : the Cart state inside the Store is constructed across multiples views (checkout different products from different pages) but when checking out the cart, we'll need to submit our Cart to the server: The Saga responsible for this operation will have to access the store to get the Cart (otherwise it'll have to reuse the Cart reducers itself to keep track of a local copy of the Cart state). So this is a case where we can allow a Saga to access the Store's state (others will disagree with this) because IMO the pros/cons balance IMO is in favor of accessing the existing state rather than duplicating the Store/reducer work. 

>It seems to me that the only way to achieve what I want is to maintain a hash of queries that my getFromServer method checks.

Yes. Where to keep this hash is related to the previous question. I would keep it inside the Saga unless we need to display it into the view

**Comment by tarjei** [comment]
Thank you for this long and thoughtfull answer! Much appreciated. 

You write:
> it's not clear from your first question if you need to
> 1. memoize xhr call results for queries to the same resource all the time
> 2. prevent requests for the same result to run concurrently ie you don't want to memoize results for all queries but just for those running concurrently at a given time
 
I think this is a bit of both as I both need to prevent multiple requests if a resource is being requested and if it has already been fetched. Also the UI needs to know it a resource is being loaded. 

I was hoping to use a simple `PUT` call to tell the store that the request is being fetched, but that didn't work out too well due to PUT not being synchronous. I ended up solving it by listening to the action triggering the saga instead and updating the state there.

I like your example of the click having to happen twice to execute the request, but in I found in inapplicable to my use case.

Anyhow, thanks for your time and answer and thanks for redux-saga.

**Comment by yelouafi** [comment]
>I was hoping to use a simple PUT call to tell the store that the request is being fetched, but that didn't work out too well due to PUT not being synchronous.

I don't see why this is a problem actually. Microtasks are always finer-grained than user events: it means even if you get 2 consecutive click events they will be processed in this order : first click -> put -> second click. Unless of course you have a code that dispatches 2 successive actions synchronously in the code like

```javascript
dispatch({type: 'FETCH', query: 'resource1'})
dispatch({type: 'FETCH', query: 'resource1'})
```

It's pretty rare but it can be the case actually if 2 Components mounted at the same time dispatches 2 requests to the same resource.

In this case you may want to store the query state inside the watcher itself (if you need to keep it in the Redux store you may also uses ana additional `put`)

```javascript
function* watchFetch() {
  const queryState = {}
  while(true) {
    const { query } = yield take('FETCH')    
    const prevTask = queryState[query]
    if( !prevTask || !prevTask.isRunning() ) {
      queryState[query] = yield fork(getFromServer, query)  
    }    
  }
}

function * getFromServer(query) {
   // if needed for the view : yield put(queryIsExecuting(...))
   yield doXhttpRequest(query)
   ... handle responses etc
}
```
