### ISSUE TITLE
missing action

### ISSUE THREAD

**Issue by baabgai** [yelouafi/redux-saga#198]
I hope I'm not duplicating any issues, but from #50 I got the impression that the use-case of synchronous actions was already resolved in v0.6+.

I'm using a custom middleware to handle API calls, more or less like from the real-world example in redux. So I dispatch an object that might look like

```javascript
function loadUserData(id) {
  return {
    types: [USERDATA_PENDING, USERDATA_SUCCESS, USERDATA_FAILURE],
    [API]: {
      endpoint: '/whatever/user'
    },
   meta: { userId: id }
  }
}
```

within the api middleware authentication, caching etc will be handled (I know the whole thing could be maybe handled with sagas, but for now we just try to migrate bits and pieces and see how it works out).
Right the start of the middleware I dispatch the pending action

```javascript
...
const [ pending, success, failure ] = action.types
dispatch({ type: pending, meta: action.meta })
...
```

In my saga now I listen to some user intent action (e.g. SHOW_PROFILE) from a component and try to make related calls along with other operations that might need to happen as a result

```javascript
...
const { id } = yield take(SHOW_PROFILE)
(typeof id !== 'undefined') ? yield put(loadUserData) : yield put(<someOtherAction>)
const { meta: { userId }} = yield take(USERDATA_PENDING)
history.push(`/app/someurl/${userId}`)
...
```  

in this scenario I miss the pending action, and the only way to take it is to wrap the dispatch call in the api middleware with a setTimeout function. 

Is this case still a limitation of the library or am I missing something to handle these use-cases correctly?

**Comment by fhelwanger** [comment]
I don't know what is expected to happen in this case, but why you need to take `USERDATA_PENDING`?

If it's always dispatched after you put `loadUserData`, I think you don't need it.

The success and failures actions being asynchronous should be taken normally.

**Comment by baabgai** [comment]
Indeed success and failure will work as expected.
In this case I tried to navigate to a different page and showing a loading spinner directly after the interaction happened and wait on the new page for the actual response.

**Comment by fhelwanger** [comment]
I think you can do that without taking the `USERDATA_PENDING` action. Navigation can be done as follow:

```js
const { id } = yield take(SHOW_PROFILE)
(typeof id !== 'undefined') ? yield put(loadUserData) : yield put(<someOtherAction>)
// You don't need it, just navigate to the other page immediately
// yield take(USERDATA_PENDING)
yield call(history.push, 'other-page')
```

The loading spinner should be shown based on your app state, which is managed by your reducer.

**Comment by baabgai** [comment]
Thanks for the suggestions, but this won't work because I need a key which is included in the meta tag of the action to get the navigation correct. I forgot to include these requirements in the original post (now its updated). I'm sure there might be other ways to work around the problem, but I was also curious to know if this is somehow expected behavior or if I been missing something, especially since I've got the impression that after v0.6 this might work.

**Comment by yelouafi** [comment]
@baabgai First let's understand why you're missing the action.

First thing to know is that the `put` effect is dispatched asynchronously in a microtask (you'll see why shortly); i.e. something like this

```javascript
function runPutEffect(action) {
  Promise.resolve().then(() => dispatch(action))
}
```

what that means in your code is that `yield put(loadUserData(...))` is not executed right away but shceduled in a microtask. so the current flow will first terminate (e.g. the code dispatching the action to the Saga) then the dispatch will be executed. 

There are various reasons for this but in this case your example doesn't work precisely because of synchronous dispatching. Here is why

Suppose that redux-saga executes the put effects syncronously (i.e right away)

```javascript
function runPutEffect(action) {
  dispatch(action)
}
```

What will happen in your example above is the following sequence

- Some code (e.g. inside an UI component) dispatches `SHOW_PROFILE`

- The Saga takes the action and yields the `put(loadUserData(...))` effect

- (We suppose) the Saga dispatches the `loadUserData(...)` action synchronously

- The action goes through the Store's middleware pipeline and intercepted by your middleware

- The middleware will `dispatch({ type: pending, meta: action.meta })`. **and this the issue**: because we're still in the middle of the first dispatch.

In other terms we've this call sequence

```
UIComponent:dispatch(SHOW_PROFILE)
-----------> Saga:take(SHOW_PROFILE)
-----------> Saga:put(loadUserData)
--------------------->Store:dispatch(loadUserData)
------------------------------->middleware:dispatch({ type: pending, meta: action.meta })
------------------------------->middleware:fires the ajax request
------------------------------->middleware:return
--------------------->Store:return
----------->Saga:take(USERDATA_PENDING)
```

so the issue here is precisely because the sequence is synchronous, when the Saga is calling put; It'll have for the dispatch call to return (Just as you wait for a `val = func()`). But since the middleware is dispatched inside the first dispatch, the Saga will not take the nested action because it's still waiting for the outer dispatch call to return.

and this is exactly what's happening in your example above: even if the Saga dispatches the action asynchronously, the whole sequence above will happen inside the same microtask (the dispatch and the nested dispatch).

So the solution is to dispatch the middleware action *after* the the saga action and not *inside* of it. And to do this you have also to dispatch your action asynchronously

```javascript
const [ pending, success, failure ] = action.types
Promise.resolve(). then( () => dispatch({ type: pending, meta: action.meta }) )
```

>I got the impression that the use-case of synchronous actions was already resolved in v0.6+.

0.6 solved the case for synchronously taking actions: i.e. the take effects will be resolved in the same task as when the action was dispatched (e.g. from a Component event handler). But the case for sync/async dispatches is more complicated (conceptually and not technically) because of the nested dispatch issue above.

I opted for the async dispatch because it provides a more predictable behavior for most of use cases. For example a common use case is for Sagas to dispatch actions at the start of the application

```javascript
function* startupSaga() {
  yield put( loadStartupData() )
}

//...
createStore(reducer, applyMiddleware( createSagaMiddleware(startupSaga, ...) ))
```

The Saga dispatches an action right at the start. If we dispatch the action synchronously, it won't work because the code above will execute inside the `applyMiddleware(...)` call, i.e. before even the `createStore` returns. 

You can also find more examples [in those test cases](https://github.com/yelouafi/redux-saga/blob/master/test/recipes/takeSync.js)

>Is this case still a limitation of the library 

TBH I can't answer this. I agree it has to do with the event model of Sagas (take/put). But I think it's also due to how Redux dispatching works. 

Will this issue be gone if Redux *flattened* itself the dispatches (for example by ordering them in microtasks) ? I don't know. But I'd like to hear what @gaearon is thinking of this

**Comment by baabgai** [comment]
Thanks a lot for the fast and detailed explanation. I had a similar issue already earlier with a thunk dispatching actions I missed, but I could work around that in a different way. Guess that was caused by the same behavior. Now it makes much more sense.

If this issue can't be considered a bug, maybe your explanations would fit somewhere in the docs (troubleshooting section?) to prevent people from running into that issue.

thanks again. saved me a lot of time getting my head around this issue.

**Comment by yelouafi** [comment]
>If this issue can't be considered a bug, maybe your explanations would fit somewhere in the docs (troubleshooting section?) to prevent people from running into that issue.

Yes I think so

**Comment by panki** [comment]
@baabgai it seems like a not too good decision. Why you need to yield put(loadUserData) instead of call api function that loads user details or returns already exists?

In this case, you split user loading logic into 2 sagas, while it should be in one place?

I think it might look like this:
```javascript
...
const { id } = yield take(SHOW_PROFILE)
if (typeof id !== 'undefined') {
    yield put(loadingUserData()) // Fires USERDATA_PENDING action
    const {userId} = yield call(api.loadUserData)
    history.push(`/app/someurl/${userId}`)
} else {
    yield put(<someOtherAction>)
}
...
```

**Comment by baabgai** [comment]
@panki that might be correct, but the reason for writing the saga as described was mainly driven by the fact that the custom api middleware (including various transformations on the requests) was already in place and I tried to fit a few sagas in our existing code base. If I had the time do more refactoring I guess this specific problem might not have manifested because you might implement it in a similar way you described.

**Comment by yelouafi** [comment]
FYI added a mention on the troubleshooting page(`The put effect is also a blocking call` section)

http://yelouafi.github.io/redux-saga/docs/Troubleshooting.html
