### ISSUE TITLE
Dynamically starting sagas

### ISSUE THREAD

**Issue by tappleby** [yelouafi/redux-saga#23]
This might have some overlap with with the `runSaga` idea mentioned in #13 ([comment](https://github.com/yelouafi/redux-saga/issues/13#issuecomment-168417279)).

Currently all sagas need to be provided during startup, I am curious if it make sense to have the ability to dynamically start them. 

After writing the example below I think the main use case would be larger apps that use code splitting, if you know all your sagas ahead of time its probably simpler to have watchers which fork based on dispatched actions (compatible with time travel).

----------------------------------------

For example if we only want the `onBoarding` saga to be running while in a specific section of our app it could be started/stopped with a container component:

```js
componentWillMount() {
  this.onBoardingTask = runSaga(onBoarding, this.props.store);
}

componentWillUnmount() {
  cancelSaga(this.onBoardingTask);
}
```

**Comment by yelouafi** [comment]
While I understand the code splitting requirement. I tend to not agree with starting sagas from inside containers elements. Perhaps, it'd be better to start the dynamic sagas in the same place we update the store. For example, if we load some dynamic module with new reducers and sagas I can imagine

```javascript
function updateAppWithNewModule(module) {
  updateStoreWithNewReducer( module.reducer )
  runSaga(module.saga)
}
```

FYI, I've already pushed changes in the master branch which include [`runSaga` support](https://github.com/yelouafi/redux-saga/blob/master/src/runSaga.js) (along with monitoring support).

**Comment by tappleby** [comment]
Yeah a component was probably a bad example (though I have been curious if `proc` could be used locally within a component to manage complex flows). I mainly wanted to show the cancelling of saga on unmount.

Starting the saga at module load time seems like the correct approach; I could see this working well with dynamic routes in react-router.

**Comment by yelouafi** [comment]
>though I have been curious if proc could be used locally within a component to manage complex flows

technically yes. actually proc has a signature like `(iterator, subscribe, dispatch) -> Promise`. So you can hookup `take` and `put` to any external input/output (aka [csp channels](https://en.wikipedia.org/wiki/Channel_(programming))). But I wouldn't recommend using an internal function, as the signature may change in the future.

This is another item on my todo list. Initially, I imagined `runSaga(iterator, {subscribe, dispatch})` which *would* work with Redux Stores out of the box. But the store doesn't actually provide the triggered action to its subscribers, and I read in a related Redux issue that this is intentional (https://github.com/rackt/redux/issues/1057).

Another solution I m considering is keeping the generic `runSaga(iterator, {subscribe, dispatch})` and exposing the utility function `storeChannel` so we'll end up with something like

```javascript
runSaga( iterator, storeChannel(store) )
```

With the benefit of being able to connect the Saga to any external channel

**Comment by tappleby** [comment]
I do like the idea of keeping it generic, would remove the need for things like `emitterFromStore` or store enhancers mentioned in #13.

Is there a common interface that other libraries seem to be using for channel like functionality? closest thing I can think of is [Rx.Subject](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/subjects/subject.md).

**Comment by yelouafi** [comment]
>Is there a common interface that other libraries seem to be using for channel like functionality? closest thing I can think of is Rx.Subject

[Node duplex streams](https://nodejs.org/api/stream.html#stream_class_stream_duplex) seems to mimics channel's take/put, but uses 2 independent channels reads/writes. It doesn't also use promises for communication

**Comment by yelouafi** [comment]
FYI. the new v0.4.0 supports `runSaga`

**Comment by tappleby** [comment]
:+1:

**Comment by guoqing2013** [comment]
看看这个： https://github.com/GuillaumeCisco/redux-sagas-injector
