### ISSUE TITLE
takeEvery doesn't work when action type is a Symbol

### ISSUE THREAD

**Issue by Zacqary** [yelouafi/redux-saga#246]
When dispatching actions with a `type` equal to a `Symbol`, `takeEvery` throws `TypeError: Cannot convert a Symbol value to a string`.
```javascript
const ACTION_TYPE = Symbol("ACTION_TYPE Debug String");
```
```javascript
// Inside a saga
yield* takeEvery(ACTION_TYPE, sagaToYield); // Throws TypeError
```

However, using `take` works fine.
```javascript
for (;;) {
    yield take(ACTION_TYPE);
    // Yield results...
}
```

**Comment by yelouafi** [comment]
The issue seems [from here](https://github.com/yelouafi/redux-saga/blob/master/src/internal/sagaHelpers.js#L49). String interpolation doesn't work for symbols

**Comment by yelouafi** [comment]
fixed by https://github.com/yelouafi/redux-saga/commit/c9c63d95a95846162a3f51739d2b9dee41bd695a

**Comment by jscinoz** [comment]
Seems to still be an issue when pattern is an array of symbols; the following line throws with TypeError: Cannot convert a Symbol value to a string:

https://github.com/yelouafi/redux-saga/blob/master/src/internal/sagaHelpers.js#L64

**Comment by bvalosek** [comment]
(highly related question to this thread)

When using a action creator function with a `toString` property, currently that is preventing `take` from working (very similar to this issue).

eg

```
const login = credentials => {type: 'LOGIN', payload: credentials};
login.toString = () => 'LOGIN';

...

take(login)
```

Or more specifically: https://github.com/acdlite/redux-actions

Is ensuring that `take(pattern)` calls `String(pattern)` like the above fixes something we could have as well?

**Comment by yelouafi** [comment]
@bvalosek What error do you get?

**Comment by bvalosek** [comment]
I realized that this can't be implemented without breaking BC with your API.

I was asking if, when passing in a function that overrides `toString` that it could be cast to a string when running the matcher... but that would break the current expectations when calling `take(fn)` (as it serves as a predicate filter in this case).

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L17

What I am doing now is that i've made a utility `const takes = p => take(String(p))` to use in all the places where i have an action creator function that returns the action type when cast to a string. If you're open to having this be a built-in Effect then I can open a PR.

**Comment by thezanke** [comment]
I found my way here looking to see if there's a way to automatically call `.toString()` on a `redux-actions` actionCreator. If this was possible I could completely drop my action type constants file (since I don't need them for reducers with redux-actions).

I think one way to get around the potential breakage that @bvalosek points out is to see if the pattern being passed to `take()` has a `toString` method of it's own (not from prototype). This could be tested with `is.func(pattern) && pattern.hasOwnProperty('toString')`. The action creators from `redux-actions` pass this test where most functions wouldn't; this would be a way to differentiate them from filters/predicates.

I could make a PR to update the definition(s) of `matchers` and/or `matcher` from `src/internal/proc.js` to make it support this.

I don't want to have to write a wrapper util and add _Yet Another Import™_ to the top of my file just to have this functionality; I also don't want to have to type `.toString()` after every action when I use `take()`.

**Comment by iMoses** [comment]
Was this issue solved?

I'm new to redux-saga and I couldn't make it work until I figured that the problem was my types were Symbols. I get no errors, no warnings, but the middleware doesn't catch any of my actions as long as the type is a Symbol.

Are Symbols not supported or is this a bug?
