### ISSUE TITLE
Handling uncaught exceptions

### ISSUE THREAD

**Issue by axelson** [yelouafi/redux-saga#250]
So I am working on a project where there are many sagas and sometimes they result in errors. In development the errors get logged to the console (which is quite nice), but in production I'd like to be able to capture the exception and send it to an error monitoring service (such as honeybadger or getsentry), is there a way to do this?

The only thing I can think of is instead of passing many sagas to `createSagaMiddleware` to only pass a single root saga and to manually capture the error in the root saga after forking every other saga. Is there another approach that I could use?

**Comment by ronanwize** [comment]
@axelson We are using an approach where our sagas will dispatch error actions to the redux store. We then have the option to use middleware to log errors, or to use other sagas to catch that and send the errors to an error monitoring service (we use sentry).

A dead simple example is like:

```
function* doSomething({payload}) {
  const output = yield call(myLongRunningFunction, payload);

  if(output.error) {
    yield put({type: 'DO_SOMETHING_ERROR', payload: output.error });
  }
}

function* doSomethingErrorWatcher() {
  while(true) {
    const errAction = yield take('DO_SOMETHING_ERROR');
    yield call(myFuncThatPostsToSentry, errAction);
  }
}
```

Naturally our code is alot more complex than that but that's the basic idea. We actually have two layers that do this, one that runs within our sagas and another that is redux middleware but that is because we have specific business requirements to log these in different places.

**Comment by axelson** [comment]
@ronanwize that's a very interesting approach! Thanks for sharing. But wouldn't this still not catch uncaught exceptions in your `doSomething()` method? For example if the `myLongRunningFunction()` did not exist, than no error would be reported.

**Comment by yelouafi** [comment]
@axelson For `fork`ed sagas you can use the `done` property to catch errors

```javascript
function* wrap(saga, ...args) {
  const task = yield fork(saga, ...args)
  task.done.catch(reportTheError) // handle the error
  return task
} 

// wrap the fork effect
const wrapFork = (saga, ...args) => call(wrap, saga, ...args)

// then use it instead of fork
function* mySaga() {
  while(true) {
    const action = take(ACTION)
    yield wrapFork(doSomething, action)
  }
}
```

you can do the same thing with `call`ed sagas by putting the call in a try/catch then rethrow the error.

**Comment by ronanwize** [comment]
Hi @axelson sorry I forgot to bring things back to catching errors - we actually decided to push that down a layer so anything running in a saga will return an error object we can test for, instead of throwing exceptions. The advantage is that we've been able to standardize our error handling but I know that approach isn't for everyone, it'll be heavily dependent on the other frameworks you're using and what you're trying to accomplish.

You saw that above, but our actual code looks more along the lines of:

```
const {output, error} = yield call(myLongRunningFunction, payload);

error && (handle the error);
output && (handle the output);
```

We didn't want to put try/catch everywhere. Since in most of our cases `myLongRunningFunction` is something that's handling promises, we squash the errors into a resolved promise that contains an error property:

```
function apiCall(etc) {
  return fetch(....).then(....)
    .then((output) => { return Promise.resolve({output}); }, 
             (error) => { return Promise.resolve({error}; });
}
```

In the above scenario, only `output` or `error` will ever exist so we get the exclusivity of the check for free.

This is what we need, but I know not everyone will want to handle errors this way. You don't really have to. You can also do as @yelouafi mentioned, which is what we originally did but wanted to reduce boilerplate and code paths requiring testing.

**Comment by Splact** [comment]
How do you avoid try catch on a race context? a SagaCancellationException could be thrown.

**Comment by tommedema** [comment]
@ronanwize re "we actually decided to push that down a layer so anything running in a saga will return an error object we can test for": how did you create a lower level layer in which you can catch all sagas' exceptions?

**Comment by granmoe** [comment]
Is it still OK to use `.done.catch` in a saga? I read in some other bug that it might not be safe to use in saga code.

**Comment by DominicTobias** [comment]
Despite billions of try/catches I find I still often run into just useless errors I have to spend ages with, just commenting out sections until I find the culprit. Maybe this will get easier when generators are native and there isn't a huge stacktrace in the generator polyfill.

![screen shot 2017-03-14 at 12 35 59](https://cloud.githubusercontent.com/assets/760314/23900921/f290af42-08b2-11e7-9920-b3ede74a90e7.png)
