### ISSUE TITLE
uncaught error from Promise.reject

### ISSUE THREAD

**Issue by chenxsan** [yelouafi/redux-saga#253]
A demo [here](https://github.com/chenxsan/redux-saga-uncaught-example).

Code related below, the `race` code mostly comes from https://github.com/yelouafi/redux-saga/issues/183:

```
import { fork, call, put, race, take } from 'redux-saga/effects'
function * api () {
  try {
    let result = yield * callWithLoadingEffect(fetchApi)
    console.log(result)
  } catch (error) {
    console.log('error', error)
  }
}
// fetch data from reddit
function fetchApi () {
  return fetch('https://www.reddit.com/new.json')
    .then(
      (response) => {
        return Promise.reject('haha')
        // return response.json()
      }
    )
    .catch(
      (error) => Promise.reject(error)
    )
}
const delay = (ms) => new Promise((resolve) => setTimeout(() => resolve(true), ms))

export function * callWithLoadingEffect (fn) {
  try {
    const task = yield fork(fn)
    const taskPromise = new Promise((resolve, reject) => {
      task.done.then(resolve, reject)
    })
    let {timeout, result} = yield race({
      timeout: call(delay, 100),
      result: taskPromise
    })
    if (timeout) {
      yield put({
        type: 'SHOW_LOADING'
      })
      result = yield taskPromise
    }
    yield put({
      type: 'HIDE_LOADING'
    })
    return result
  } catch (err) {
    yield put({
      type: 'HIDE_LOADING'
    })
    throw err
  }
}
export function * helloSaga () {
  console.log('Hello Sagas!')
  while (true) {
    yield take('FETCH')
    yield fork(api)
  }
}
```
If I returned `Promise.reject('haha')` when response comes back, `proc.js` would print errors:

<img width="934" alt="screen shot 2016-04-10 at 18 28 27" src="https://cloud.githubusercontent.com/assets/1091472/14409588/4fb350f8-ff4a-11e5-9727-0f8301e7faf8.png">

I thought the `try {} catch () {}` in `callWithLoadingEffect` would catch the error as [doc](http://yelouafi.github.io/redux-saga/docs/basics/ErrorHandling.html) said, and from the console, I can see `api` generator did catch the error, but that `uncaught haha` seems like that it isn't true, any suggest? 

Thanks.

**Comment by chenxsan** [comment]
The problem happened in line:

```
result = yield taskPromise
```

**Comment by chenxsan** [comment]
I just made some tests with [real world example](https://github.com/yelouafi/redux-saga/blob/6c6ad42c7b53fa8ce419bfdccab78d508e862e99/examples/real-world/services/api.js#L44), changed the line to:

```
response => Promise.reject(response),
```
then I got a same error in console:

<img width="623" alt="screen shot 2016-04-10 at 23 06 03" src="https://cloud.githubusercontent.com/assets/1091472/14411080/ea474540-ff70-11e5-9b40-6e3e77106c9d.png">

**Comment by chenxsan** [comment]
A workaround here is to return a plain error object instead of rejecting or rethrowing the error:

```
// fetch data from reddit
function fetchApi () {
  return fetch('https://www.reddit.com/new.json')
    .then(
      (response) => {
        return {error: 'haha'}
        // return response.json()
      }
    )
    .catch(
      (error) => ({error})
    )
}
```

**Comment by yelouafi** [comment]
Actually redux-saga logs *all* rejections inside a Saga. In the code you're forking a call to `fetchApi` (which is automatically wrapped in a generator), so when `fetchApi` fails with a rejection, the middleware automatically logs the error.

Maybe we should change this because sometimes the developers want to bubble up the error intentionally. So we can keep the error logging only for forked tasks (because there is actually no way to catch errors from forks). So this will would work only for called and joined tasks (although it's be hard to determine this in the above example since you're not joining the original task but only a *copy* of its done promise)

**Comment by chenxsan** [comment]
Since the loser in the `race` would be cancelled automatically so that code I copied from https://github.com/yelouafi/redux-saga/issues/183 is kinda a workaround to get the loser's eventual result (I might misunderstand something here).

In my case I just wanna throw the errors out, letting it bubble up, then I can handle the errors in their own scope.

**Comment by yelouafi** [comment]
>Since the loser in the race would be cancelled automatically so that code I copied from #183 is kinda a workaround to get the loser's eventual result (I might misunderstand something here).

I understand. since I plan to add a non destructive `race` version, I think this wont be an issue.

So IMO the solution would be to log only uncaught exceptions from *top level tasks* which in our case corresponds to forked (and non joined later) tasks

**Comment by yelouafi** [comment]
>In my case I just wanna throw the errors out, letting it bubble up, then I can handle the errors in their own scope.

Just to be precise. This affects only the logging behavior (which may be confusing of course). The errors are still bubbled up

**Comment by chenxsan** [comment]
I'm using redux-saga in our react-native project, since react-native would show a frightening red error page when there're any uncaught errors, so it's a little annoying :).

**Comment by yelouafi** [comment]
I agree on this. Already posted a fix on the master branch. The errors are now logged only for forked tasks, and if a task was joined then errors will no longer be logged until they propagate to a top level task.

I'll also add the non destructive race effect for the next release

**Comment by yelouafi** [comment]
v0.10.0 has a new fork model. Errors now bubble up the fork/call chain and are logged only at the top level task. Since the new version no longer depends in promises to handle task ending I suggest you use join(task) whenever you want to wait for a task. In a race only the join will be cancelled

**Comment by chenxsan** [comment]
@yelouafi Thank for your hard work and the suggestion. :+1:

**Comment by chenxsan** [comment]
@yelouafi Sorry, I read the whole conversation again, and found I'm a little confused with this now:

>  So we can keep the error logging only for forked tasks (because there is actually no way to catch errors from forks).

Does it mean I should never throw errors inside the forked function? If the answer is yes, that could be a tough restraint.

**Comment by yelouafi** [comment]
The error will actually bubble to parent. But there is no  way for the parent to catch errors from forked tasks: the parent has its own flow in its body. And the parent may have already terminated its body. The only way I think you can handle errors on a forked task is by catching it in the fork itself

Of course nothing of the above is set in stone:)

Are there use cases which implies catching errors from forks?

**Comment by yelouafi** [comment]
Oops! Sorry THERE is actually one way to catch errors from forks: say p1 `call(p2)` then p2 `fork(child)`  if child aborts you can't catch the error from p2 (b/c it's parallel to the main p2 body). But you can catch it from p1

**Comment by chenxsan** [comment]
So if you `fork` something, you won't be able to catch the error inside where you `fork`ed them since they are in different context now.

I'm running the api call in `fork` since I want to get the result later even it's not winner in the `race`.

1. Run a `race` between a timeout and the api `fork`
2. If timeout wins, put up a loading indicator on the screen
3. Once the api `fork` resolve/reject, return the result to whoever called it and hide the loading indicator.

```
export function * callWithLoadingEffect (fn) {
  if (typeof fn !== 'function') {
    throw new Error('callWithLoadingEffect only accept function as its argument')
  }
  try {
    const task = yield fork(fn)
    let {timeout, result} = yield race({
      timeout: call(delay, 20),
      result: join(task)
    })
    if (timeout) {
      yield put(loadingShow())
      result = yield join(task)
    }
    yield put(loadingHide())
    return result
  } catch (err) {
    yield put(loadingHide())
    throw err
  }
}
```

If any errors `throw`ed inside the api `fork`, I want to catch it - I think this is a valid use case :).

**Comment by yelouafi** [comment]
I think you can get the same effect and a simpler code with try/finally

```javascript
export function * callWithLoadingEffect (fn) {
  if (typeof fn !== 'function') {
    throw new Error('callWithLoadingEffect only accept function as its argument')
  }
  try {
    const task = yield fork(fn)
    let {timeout, result} = yield race({
      timeout: call(delay, 20),
      result: join(task)
    })
    if (timeout) {
      yield put(loadingShow())
      result = yield join(task)
    }
    return result
  } finally {
    yield put(loadingHide())
  }
}
```

IMO, you shouldn't use any try/catch with a join effect. The main purpose of a join is to wait for a task to terminate. The task should handle all its errors and let only bubble unexpected ones (see below)

I'd rather separate errors in 2 classes

- Business errors are *expected errors* and should be handled inside the forked task itself.

- Bugs are *unexpected errors* and will simply bubble up the fork chain up to the root. All sagas in the current execution tree will be cancelled and the error will bubble up. I can't see how a program can recover from a bug. The only options I think of is to show some message to the user that the app has encountered an unexpected error, send some report then close the app to avoid any inconsistent state.

At least the best way to work with the redux-saga fork model is to handle business errors from inside the forked tasks themselves an let bubble only bugs which can be caught at some higher level. 

In fact I can even go farther and recommend to not use try/catch for business error handling because javascript IMO lacks the necessary constructs for typed catch blocks. consider this code

```javascript
function* myCallabletask() {
  try {
    yield call(Api.gett) // note typo
    yield put(RequestSuccess)
  } catch(err) {
    yield put(RequestError) // will put on any kind of error including Runtime errors/bugs
  }
}
``` 

because the catch block catches all errors: both business Errors (server error, timeout ...) and bugs (Api.gett is not function). The code reacts the same on both types; I don't think this the desired behavior. Typically we want to put an Error action only on server errors and let bubble any bug. In typed languages like Java you can achieve this with typed catch blocks  like`catch (ServerError err)` But JS lacks this feature.

The best way to think of the fork model is as dynamic parallel effect. A saga has a *main flow* (its own body => the main task) and can fork parallel flows dynamically. Like in parallel effects, cancelling the saga will cancel all the parallel tasks (main task + forked tasks). The saga will terminate after all parallel tasks terminate, and an error from one of the tasks will abort the whole parallel effects. 

It may sound restrictive but this has the advantage of having a much simpler model to reason about. You know precisely how do Return values, Errors and Cancellations propagate, ... The other option is the very flexible Promise model but also its well known issues (esp. Error propagation => unhandled rejections, error swallowed, not to mention the difficulty to define a simple and consistent model for Cancellations)

**Comment by chenxsan** [comment]
Thanks, I think it makes sense to separate those errors in my code.
