### ISSUE TITLE
Should we use saga for updating UI state and redirecting users after actions?

### ISSUE THREAD

**Issue by jshthornton** [yelouafi/redux-saga#262]
Say that you have a form to submit.
This form needs to perform an async operation, then depending on the result either go to another scene or display an error.

The error part is simple using FSA, but for going to another scene is it recommended to still include that in the saga?

**Comment by slorber** [comment]
@jshthornton for me it's a valid usecase. I do this kind of stuff extensively to build onboardings where we have to guide the user to a specific workflow that should only be applied just after signup.

**Comment by ronanwize** [comment]
@jshthornton this is what we do. In our completion sagas, we simply emit the appropriate redirect via react-router.

**Comment by secobarbital** [comment]
In order to keep the navigation logic inside the component, I send a `onSuccess` callback in the action, which the saga can call upon completion. This pattern does pollute the action with a non-serializable function.

**Comment by jshthornton** [comment]
@secobarbital I think in regards to the non-serializable part FSA is to the rescue. Use payload for the actual serializable data, and then the meta for anything which just surrounds it.

So:

```
{
  type: 'ACTION',
  payload: {
    id: 1
  },
  meta: {
    updateUI: function() ...
  }
}
```

**Comment by secobarbital** [comment]
@jshthornton Indeed, that is what we do!

We haven't actually had to serialize actions yet so we haven't thought about serializability of payload vs meta, but I will certainly keep your comment in mind when we need to.

In this case the callbacks definitely belong in `meta` as they are not part of the form inputs being submitted.

**Comment by floriangosse** [comment]
I started with common saga like a login flow and implemented custom actions and sagas for specific containers.
These UI sagas trigger the common action and take the success/failure actions for redirect to the correct url. With this solution we can split the BL from UIL (UI-Logic).

**Comment by alex-shamshurin** [comment]
Under certain circumstances redirect might be done in Sagas on server via promises(rendering wait unlil saga's functions finished), because onEnter hooks in routes happens before match() and before sagas. So in OnEnter callback it is very easy to redirect but we are at "before" state and away from all sagas and all system logic. whereas in sagas all our BL lives.

**Comment by mmcc** [comment]
I know this is an old issue, but we started to go down the path of this thread (callback functions in the `meta` key), but ended up going a slightly different direction.

In order to be able to serialize our action in its entirety, instead of a callback _function_, we ended up going with a callback _action_ that we dispatch at success.  This has been particularly handy in how we do things like delete confirmation. Here's an example:

```
function *deleteThing (action: Action<'ThingDeleteRequested'>) {
  const { payload: { id }, meta: { callbackAction } } = action;

  yield put({ type: 'ConfirmAction', payload: { actionType: action.type } });
  const { canceled } = yield race({
    confirmed: take('ActionConfirmed'),
    canceled: take('ActionCanceled'),
  });

  if (canceled) {
    yield cancel();
  }

  try {
    yield call(Api.Things.deleteThing, id);
    yield put({
      type: 'ThingDeleted',
      payload: { id },
    });
    yield put(callbackAction);
  } catch (error) {
    yield put({ type: 'APIRequestFailed', payload: { error } });
  }
}
```

This is nice because it allows us to have that action live at the caller, which is required if we want to redirect different places (or not at all) based on where the action is dispatched from.
