### ISSUE TITLE
Exceptions being lost silently in 0.9.5 package on npm

### ISSUE THREAD

**Issue by danwad** [yelouafi/redux-saga#264]
Due to this line: https://github.com/yelouafi/redux-saga/blob/v0.9.5/src/internal/proc.js#L321

This is fixed in master, but it may be worth publishing this version to npm sooner since this is catching exceptions and not reporting anything in console. It makes hunting down some bugs a bit tricky.

Installing from github with `npm install yelouafi/redux-saga` did not work. Had to clone and use `npm link`

**Comment by netfishx** [comment]
+1

**Comment by yelouafi** [comment]
The master branch contains many more changes. Since the fork model was totally reimplemented, it'll be possible to propagate errors from forked tasks just as we do with normal functions. So no error should be swallowed, uncaught errors will propagate up to the top parent. I've also improved a bit error reporting to log the entire *saga stack*.

![error-rep](https://cloud.githubusercontent.com/assets/5453835/14715139/a221fe50-07df-11e6-9fd7-0122d5859c3f.png)

It's almost finished, I'll try to release this ASAP

**Comment by yelouafi** [comment]
See v0.10.0
