### ISSUE TITLE
CRUD Sagas: Best Practices?

### ISSUE THREAD

**Issue by chapati23** [yelouafi/redux-saga#268]
Just wrote my first saga + specs but feeling kinda unsure if this is the correct approach:
https://gist.github.com/chapati23/970ee7adde20606e902e48f867b4ed4f

Could only find bits and pieces of CRUD in the examples. My guess is that interacting with APIs is a prime use-case for redux-saga so it might be worthwile to add an example e.g. `examples/api-saga`

Also, I know this isn't StackOverflow, but of course I'd be happy about feedback on the saga I wrote if I got something overly wrong :)

**Comment by smastous** [comment]
It looks pretty good to me.  The only thing you might want to do is add a FETCH_GRID_PENDING action so that you can easily show a loading indicator or something like that.

``` javascript
export function* fetchGrids(action) {
  try {
    yield put(actions.fetchGridPending())

    const grids = yield call(api.GET, 'grids')
    yield put(actions.fetchGridsSuccess(grids))
  } catch (error) {
    yield put(actions.fetchGridsFail(error))
  }
}
```

You can also abstract these api calls out into a helper that might look something like:

``` javascript
export function* callApi(apiCall, pendingAction, successAction, rejectedAction, onSuccess=()=>{}, onRejected=()=>{}) {
  try {
    yield put(pendingAction)

    const result = yield call(apiCall)
    yield call(onSuccess, result)
    yield put(successAction(result)

  } catch (error) {
    yield call(onRejected, error)
    yield put(rejectedAction)
  }
}
```

Then, create would become something like:

``` javascript
  export function* createGrid(action) {
    yield fork(callApi, callToYourApi, actions.createGridPending, actions.createGridSuccess, actions.createGridFail, 
function*(grid){yield put(actions.closeSubview()) })
}
```

Honestly though, in your case the code is so nice and straightforward already that I don't feel like the added abstraction is really worth it.  I can look at your gist and immediately understand what its doing, which is more valuable than saving a few lines of code.

**Comment by chapati23** [comment]
Thanks for the feedback, I set "loading" as a state in my reducer as soon as an async action gets dispatched so I don't think I need an extra LOADING action. Glad to hear I did it right, so closing this :)
