### ISSUE TITLE
Long error messages should be cut in production

### ISSUE THREAD

**Issue by gaearon** [yelouafi/redux-saga#298]
As noted by @blesh in https://twitter.com/BenLesh/status/727659194711597056, we should gate long error messages:

```js
if (process.env.NODE_ENV === 'production') {
  throw new Error('short message');
} else {
  throw new Error('long message');
}
```

This way Uglify can dead-code eliminate the long version in the minified builds.

**Comment by yelouafi** [comment]
Makes sense. I was wondering if uglify does this by default

**Comment by slorber** [comment]
@gaearon you mean DefinePlugin / Envify? not sure Uglify does such thing

**Comment by slorber** [comment]
Also, for those like me logging all production errors in GetSentry, it's better to not do like React and still have meaningful errors in production, otherwise what we log in GetSentry is useless. A short message or an error code is relevant, but a generic "redux saga error" would be bad

See also https://github.com/facebook/react/issues/2686

**Comment by gaearon** [comment]
Yeah, I meant that this project already envifies with DefinePlugin so adding a condition is enough to get this eliminated with Uglify.

**Comment by gaearon** [comment]
How it usually works: DefinePlugin/envify just replace `process.env.NODE_ENV` with a string. However it is Uglify that actually removes `if ('production' !== 'production')` blocks as dead code.

**Comment by yelouafi** [comment]
@gaearon Thanks for the clarification. I'll add this in the next patch

@slorber
Agree but I think in cases like the one in the tweet above it's not necessary. Because the errors are related to the app startup itself. It's very unlikely that the app will be shipped in production with that type of errors.

**Comment by gaearon** [comment]
The one important thing is to how consistent throwing behavior in dev and prod. Giving a shorter message in prod is fine, but throwing only in dev is problematic because it makes app behaves inconsistently.
