### ISSUE TITLE
How to catch global saga errors

### ISSUE THREAD

**Issue by hoschi** [yelouafi/redux-saga#343]
I know how to handle expected errors within a saga, this is not the problem.

I have effects which can produce errors, which should "never" happen. E.g fetch user profile information. This ajax call only fails if the api server isn't running.

These errors are handled in
https://github.com/yelouafi/redux-saga/blob/ae39cf06dee57ddd3db935a0023db5f584eb1748/src/internal/proc.js#L243
which logs the error to the console. Is this overwritable to e.g. dispatch an action to show the error to the user or send it to a error logging backend API?

**Comment by pavelkornev** [comment]
Have you tried like so:
```
store.runSaga(rootSaga).done.catch((e) => {
  console.log(e.message)
})
```

**Comment by yelouafi** [comment]
I think what @hoschi  is asking is a 'generic' way to handle errors inside tasks. Catching the error on the root saga will abort all the currently executing tasks on the execution tree. The same observation holds for the above snippet in proc.js, when you reach that point it's too late because all the tasks in the way have already been canceled.

redux-saga follows the same synchronous style for handling errors, so in order to handle some errors in a generic way you'll have to implement a generic saga for handling those errors and then call it inside your catch blocks. A better way IMO, is to not use try/catch to handle application errors and use explicit return values instead. JavaScript hasn't good support for try/catch as it doesn't provide Typed catch blocks. so your catch block can swallow also application bugs (e.g. undefined var)

**Comment by hoschi** [comment]
It is OK when the hell breaks loose and nothing works at this moment in the browser. I *just* want to send as much information as I can above this error to a logging service to:
* know I have a bug
* get information about the bug

When the solution of @pavelkornev catches the error before the logger in proc.js, this is the "good enough" solution for my use case.

Initially I thoght it would be more complicated to catch these kind of errors and I wanted to reuse the existing code of proc.js, but replace `console.log` with `sendToBackendLogger`. Perhaps this was confusing.

**Comment by hoschi** [comment]
This works in the way mentioned, but good enough for me, thanks.
