### ISSUE TITLE
Redux-Saga can help ajax request-response squence issue?

### ISSUE THREAD

**Issue by minhyeong-kim** [yelouafi/redux-saga#367]
Hello :)

Recently i met AJAX response sequence problem for dispatching single property in redux single store.

Each dispatching process work with below action sequence.

```
1. Change browser location by history API and Router.onEnter invoke action creator (react-router)

2. 'FETCH_OBJECTS_REQUEST'    // dispatching before request ajax. (no data update)

3. axios.get('/api/file/{objectId}')   // fetching data

4. 'FETCH_OBJECTS_SUCCESS'    // update single store

4-1. 'FETCH_OBJECTS_FAIL'    // just show errors
```

The problem is. API response time depend to 'objectId' parameters.

For example. each `/file/{objectId}` takes time to `/file/A` -> 1s, `/file/B` -> 5s.

User access to `/file/A` page. and move to `/file/B` by click some links and go back by browsers 'back' button immediatly.

In this case.

API request order

```
0--------------1--------------2--------------3--------------4--------------5
[/file/A]  [/file/B]  [/file/A]
```

API response order will be 

```
0--------------1--------------2--------------3--------------4--------------5
               [/file/A]        [/file/A]                          [/file/B]
```

Browser location will be `/file/A`. but result of `/file/B` reducer. store data fill with B object data.

So i plan to validate each response by 'currentObjectId' and 'lastAPIToken' before reducing them. For example, after third request sent. the state will be `currentObjectId: 'A', lastAPIToken: '3'`. then every reducer validate response data whether matched with flag state before dispatch. so response of first `/file/A` and last `/file/B` will be ignored.

Instead of make upper validation. Is Redux-Saga can help this situations? as i expected, `takeLatest` accept second response?

**Comment by kuy** [comment]
When you use `takeLatest` utility function, it just cancels the last forked task. So you can't receive the second response.

But I think `takeLatest` function can be used to help your situation. Your solution without using redux-saga has the state that contains `lastAPIToken` property to check whether it's the latest response.

On the other hand, you don't need to have `lastAPIToken` prop in the state if you use `takeLatest` function. It manages which task you launched last internally and cancels the in-flight task automatically when you launch a second task. If you want to track cancelled requests, you can write it down with [effect primitives](http://yelouafi.github.io/redux-saga/docs/api/index.html#effect-creators) because `takeLatest` function is not an effect primitive, just [a helper function](http://yelouafi.github.io/redux-saga/docs/api/index.html#takelatestpattern-saga-args).

**Comment by minhyeong-kim** [comment]
@kuy Your 'task' mean, each request-response sessions? So there is 3 task in those examples?

```
REQUEST
0--------------1--------------2--------------3--------------4--------------5
[/file/A]  [/file/B]  [/file/A]
 Task1       Task2       Task3

RESPONSE

0--------------1--------------2--------------3--------------4--------------5
               [/file/A]        [/file/A]                          [/file/B]
                Task1             Task3                              Task2
```

**Comment by kuy** [comment]
Yes! In redux-saga context, both "task" and "saga" terms express the same thing. Your example has 3 spawned tasks from `takeLatest` function.

**Comment by kuy** [comment]
Like this.

```es6
function* runRequest({ payload }) {
  const { id } = payload;
  const { data, error } = yield call(callAPI, id);
  if (data && !error) {
    yield put({ type: FETCH_OBJECTS_SUCCESS, data });
  } else {
    yield put({ type: FETCH_OBJECTS_FAIL, error });
  }
}

function* rootSaga() {
  yield* takeEvery(FETCH_OBJECTS_REQUEST, runRequest);
}
```

**Comment by minhyeong-kim** [comment]
@kuy No need to response validation logic (as i mentioned) or request-response(task, saga) matcher before yielding `put({type: FETCH_OBJECT_SUCCESS})`?

I'll prototyping this feature. and report result to this issue. Thank you very much @kuy.

If i can solving this problem without any implementation. (mean creating plugin or extension to redux-saga) i'll use redux-saga and remove all response validation logic in reducers. (i think this increase code complexity)

**Comment by kuy** [comment]
@minhyeong-kim Yes, you don't need to write validation logic because the previously spawned task is always cancelled by `takeLatest` function internally.

![redux-saga-takelatest](https://cloud.githubusercontent.com/assets/151614/15804101/3b94db22-2b38-11e6-8f99-84bf68772055.jpg)

1. `[A]` Task A is spawned by `FETCH_OBJECTS_REQUEST` action
2. `[A']` Receive AJAX result and Task A was finished successfully
3. `[B]` Task B is spawned (there is no running tasks at this time)
4. `[C]` Before Task C is spawned, Task B (waiting AJAX response) is cancelled. Then Task C is started.

**Comment by minhyeong-kim** [comment]
@kuy I got it. your comment are good to understand problems. i appreciate for your effort.

**Comment by kuy** [comment]
@minhyeong-kim Can you close this issue? If you have other problem, please ask me 😄

**Comment by minhyeong-kim** [comment]
@kuy Sure :)

**Comment by yelouafi** [comment]
@kuy Appreciate your help (and other contributions). Thanks!

**Comment by mskims** [comment]
those mentions helped me to understand saga alot! thanks
