### ISSUE TITLE
Integrating with redux router

### ISSUE THREAD

**Issue by cherta** [yelouafi/redux-saga#37]
First of all thanks for putting this together, I really like the sagas idea. I have a question and don't know if this is the best place but here it goes anyway.

I'm trying to integrate with redux-router, the idea is to be able to `take` redux-router actions and `put` a new action if necessary.

```javascript
import { pushState } from 'redux-router'
import ROUTER_DID_CHANGE from 'redux-router/lib/constants'
import * as actions from '../actionCreators'
// sagas/index.js

export function* watchNavigate() {
  let action = null
  while(action = yield take(ROUTER_DID_CHANGE)) {
    yield put(actions.show(action.payload.pathname)) //navigate
  }
}

//...
```

The main idea is to be able to react to a route change event like hitting the browser back button.

Is there any way to do it? I tried and all my actions can be `take`en but none of the redux-router ones, I'm certainly missing something.

Thanks in advance.

**Comment by yelouafi** [comment]
I didn't work with redux-router before; but it's likely because the action can't reach the middleware.

Can you show me you store setup ? I suspect some issue related of using multiple store enhancers

**Comment by cherta** [comment]
I think you are right @yelouafi. it uses an enhancer.

Here is the store setup, please let me know if you need anything else:

```javascript
import { createStore, compose, applyMiddleware } from 'redux'
import thunk from 'redux-thunk'
import { persistState } from 'redux-devtools'
import { reduxReactRouter } from 'redux-router'
import { createHistory } from 'history'
import DevTools from '../containers/DevTools'
import rootReducer from '../reducers'
import rootSaga from '../sagas'
import sagaMiddleware from 'redux-saga'

//store/configureStore.js

export default function configureStore(initialState) {

  let finalCreateStore = null

  if(process.env.NODE_ENV === 'development') {
    finalCreateStore = compose(
      applyMiddleware(
        thunk,
        sagaMiddleware(rootSaga)
      ),
      reduxReactRouter({
        createHistory: createHistory
      }),
      // Lets you write ?debug_session=<name> in address bar to persist debug sessions
      persistState(window.location.href.match(/[?&]debug_session=([^&]+)\b/)),
      DevTools.instrument()
    )(createStore)
  } else {
    finalCreateStore = compose(
      applyMiddleware(
        thunk,
        sagaMiddleware(rootSaga)
      ),
      reduxReactRouter({
        createHistory: createHistory
      })
    )(createStore)
  }

  return finalCreateStore(rootReducer, initialState)
}
```

**Comment by mjrussell** [comment]
@cherta many people are moving towards `redux-simple-router` which uses a middleware approach rather than a store enhancer and will work with React-Rotuer v2. You might give that a shot instead.

I like this approach as well because you could create a saga that does things like preventing users from going to `/object/:objectId` when `objectId` is invalid due to your store. Currently that logic has to get pushed into the connected components which seems like the wrong place for such actions.

**Comment by cherta** [comment]
Thanks @mjrussell, I tried `redux-simple-router` some time ago but ended up not using it because the little information the change event had, I can now give it another shot now that I understand the differences in more depth.

**Comment by mjrussell** [comment]
@cherta they just supported the full location object in the 2.x release which is far better than they had previously. The only thing now thats missing is the router param id auto parsing.

**Comment by cherta** [comment]
Great @mjrussell! I'll give it a try then, you convinced me :smiley:

**Comment by mjrussell** [comment]
Please let me know how it ends up working for you, I'm pretty interested in using sagas with routing (just haven't gotten to it quite yet) so I'd  be very interested to hear how it end up working

**Comment by cherta** [comment]
Sure thing!

**Comment by slorber** [comment]
Hey,

I've always had troubles to understand all the fame around React Router.
Is there really any advantage of declaring routes into JSX? "Hey we are already using JSX, let's do everything in JSX it's better than JS/JSON/XML"

Also I don't like at all the idea of letting side-effects trigger state changes: why should the url change even before your app state! If you consider the url bar/browser history as a "controlled input" (like a form input) then you should always update your Redux state before even updating that url/history.

Also, if you want clean looking urls and complex routing, I don't understand how the content of the url itself can be enough to contain all the routing state.


What I suggest:
- Never touch the url bar before updating redux state: make it controlled (the url bar content should be in redux store)
- On app start, fire an event with the initial url
- On link clicks, fire actions, rather than triggering browser history apis imperatively. Is it really the responsibility of a given component to update your app's url?
- On routing state pop (back/forward nav), just publish "routing state popped" and let a saga decide what to do


Also I generally suggest that components only describe what has happened inside them instead of embedding the translation layer (raw dom event -> business intent). See also http://stackoverflow.com/a/34623840/82609

**Comment by cherta** [comment]
Hey @slorber thanks for jumping in, I think what you are describing is exactly what @mjrussell and I wanted to do, dispatch an action, `take` it inside a saga and only then `push` the url change. That was also my original idea and why I wanted to make it play with react redux.

What you describe can be done with or without the redux routing components, the interesting part of having a router that plays nice with redux is that you gain actions that you can reduce or -in this case- create effect after them.

Just as a follow up I'm preparing a gist showing how I made it work with simple-react-redux both for user triggered actions and back/forward button support.

**Comment by cherta** [comment]
Hey @mjrussell I did a follow up on this and came out with a solution using redux simple router, probably not the best one out there but a decent one I think.

https://gist.github.com/cherta/6e2890b3dc561dcc6a58

**Comment by mjrussell** [comment]
@cherta thanks! This is definitely cool. I was thinking of using saga in a slightly different way (rewriting the url on invalid selections) but its helpful to see your approach here!

**Comment by cherta** [comment]
You are welcome @mjrussell, please if you have the time I would like to see a different approach than mine!

**Comment by yelouafi** [comment]
@cherta Thanks for your example. There is also an example of integrating react-router with sagas in the real-world example. It only use history api (one drawback though: it doesn't play nice with devtools)

I tend to agree with @slorber. It feels like react-router way is somewhat short-circuiting the data flow in Redux applications.

**Comment by mjrussell** [comment]
If you use Redux-simple-router you actually can replay history (except currently for POP operations because its already been popped off).

I agree React-Router alone can kind of feel that way, however efforts like [redux-router](https://github.com/acdlite/redux-router) and [redux-simple-router](https://github.com/rackt/redux-simple-router) are trying to be more "redux-pure" and have the store drive the url bar

**Comment by garajo** [comment]
The above did not work for me. This worked correctly and expert-recommended, https://github.com/davezuko/react-redux-starter-kit/issues/552#issuecomment-183973195
