### ISSUE TITLE
Cancel doesn't seem to trigger generator exceptions in subtasks

### ISSUE THREAD

**Issue by benturner** [yelouafi/redux-saga#375]
I'm new to `redux-saga` so apologies if I'm simply missing something obvious, but I've taken the code from https://github.com/yelouafi/redux-saga/blob/master/examples/cancellable-counter/src/sagas/index.js and reworked it just a little to run in node 4 without babel and just run from the command line. The code is here: https://gist.github.com/benturner/5d3917773a3194be551628a2756ec55a.

Notice that the output shows that `watchIncrementAsync` is properly canceled after the `CANCEL_INCREMENT_ASYNC` command is issued, exactly as expected. However, neither `incrementAsync` nor `countdown` are canceled, and they both continue to run.

What am I missing here?

**Comment by yelouafi** [comment]
Your gist seems to work correctly in jsbin. what Node version are you using?

**Comment by benturner** [comment]
This is node 4.4.5 (LTS)

**Comment by lieut-data** [comment]
I believe I'm running into a similar problem (or misunderstanding) where `yield cancel( task )` with `task = yield fork( ... )` doesn't cancel the task at all, but `task.cancel()` does.

**Comment by yelouafi** [comment]
the issue is that `generator.return()` is not supported until Node v6; see https://kangax.github.io/compat-table/es6/#node6. the `generator.return()` method is used by the middleware to jump to the finally block

Right now, the middleware simply terminates the saga if there is no `return` method on the generator. Which means the yields in the finally block as well as `chan.close` (which cancels the interval) are never executed

perhaps I should throw an error if there is no `return` method instead of simply terminating the saga

**Comment by benturner** [comment]
Wouldn't it work to use `generator.throw(new Error(...))` instead if `generator.return()` isn't supported?

**Comment by yelouafi** [comment]
This will be a lot complicated; cancellation propagation logic is handled in multiple parts in the code. You should use a pollyfill like babel-polyfill

**Comment by benturner** [comment]
Ok. I'd suggest adding that to the docs somewhere, but since Node v6 is entering LTS soon I don't think it's worth worrying about on your end. Thanks!
