### ISSUE TITLE
Forked tasks can't always take actions from its siblings

### ISSUE THREAD

**Issue by axelson** [yelouafi/redux-saga#413]
Original Reference: https://github.com/yelouafi/redux-saga/issues/277#issuecomment-228443152

I would expect this code to work as-is.

``` js
export default function * rootSaga () {
  yield fork(watchPing)
  yield put({type: 'PING', val: 0})
}

function * watchPing () {
  yield * takeEvery('PING', ackWorker)
  // yield * fixedTakeEvery('PING', ackWorker)
}

let first = true

function * ackWorker (action) {
  // yield Promise.resolve()
  if (first) {
    first = false
    yield put({type: 'PING', val: action.val + 1})
    yield take(`ACK-${action.val + 1}`)
  }
  yield put({type: `ACK-${action.val}`})
}

export function * fixedTakeEvery (actionType, saga) {
  const worker = function * (...args) {
    yield Promise.resolve()
    yield fork(saga, ...args)
  }
  yield * takeEvery(actionType, worker)
}
```

The above code results in PING, PING, ACK-1. But if you uncomment the yield Promise.resolve() or switch from takeEvery() to fixedTakeEvery() you will get the full sequence of PING, PING, ACK-1, ACK-0.

I tried to put this into an actual test case, but I'm getting different behavior (although the test is still failing).

``` js
test('inter-saga fork/take back from forked child 3', assert => {
  assert.plan(1);

  const actual = []
  const chan = channel()

  const middleware = sagaMiddleware()
  const store = createStore(() => {}, applyMiddleware(middleware))

  let first = true

  function* root() {
    yield [fork(watchPing)]
  }

  function* watchPing () {
    yield * takeEvery('PING', ackWorker)
    // yield * fixedTakeEvery('PING', ackWorker)
  }

  function* ackWorker (action) {
    // yield Promise.resolve()
    if (first) {
      first = false
      yield put({type: 'PING', val: action.val + 1})
      yield take(`ACK-${action.val + 1}`)
    }
    yield put({type: `ACK-${action.val}`})
    actual.push(1)
  }

  function* fixedTakeEvery (actionType, saga) {
    const worker = function * (...args) {
      yield Promise.resolve()
      yield fork(saga, ...args)
    }
    yield * takeEvery(actionType, worker)
  }


  middleware.run(root).done.then(() => {
    assert.deepEqual(actual, [1,1],
      "Sagas must take actions from each forked childs doing Sync puts"
    );
    assert.end();
  })

  store.dispatch({type: 'PING', val: 0})
  store.dispatch(END)
});
```

In the test case actual ends up with just `[1]` which is expected. But I would expect that uncommenting the `yield Promise.resolve()` would give `[1,0]`, but instead it gives `[]`.

**Comment by yelouafi** [comment]
The issue is not caused by `takeEvery` missing `PING` actions; you can check it by simply inserting a `console.log` statement at the beginning of `ackWorker`. You'll see that the 2 workers are forked which means that `takeEvery` caught the 2 `PING` actions.

The issue is caused by the scheduling algorithm of redux-saga. Internally the middleware tries to 'reorder' the Effects so to make it look like the forked tasks are ran in parallel, fundamentally because JavaScript is single threaded, and redux-saga resolves effects synchronously (b/c doing it with Promise scheduling causes a lot more problems than it solves, a well known issue in older versions of the lib)

for example when executing a fork Effect, the library setup a 'lock' so any `put` Effect executed within the stack frame of a fork will be delayed until the fork completes and the next effect executed (this is explained in https://github.com/yelouafi/redux-saga/issues/277#issuecomment-216083937). For example

```js
function* watcher() {
  while(true) {
    yield take('PING')
    yield fork(worker)
  }
}

function* worker() {
  // ... non blocking stuff
  yield put('PING')
}
```

The worker's `put` is executed inside the the stack frame of watcher's fork, so the put is delayed until the worker resumes and executes the take Effect. then the lock is released, the put is then executed and can be taken by watcher. This is precisely what prevents `takeEvery` from missing actions from its forks.

I'll have to review the scheduling code in order to account for the case above (like the above). This is not a simple problem. You'll see there are already [a bunch of test cases](https://github.com/yelouafi/redux-saga/blob/master/test/proc/takeSync.js) solved by the actual solution and any fix must not break the previous test cases.

As for the proposed solution, it'll solve the above issue for sure but can break existing behavior; For example

```js
function* watcher() {
  yield takeEvery('PING', worker)
  yield put({type: 'PONG'})
}

function* worker() {
  yield take('PONG')
}
```

If we delay the worker by a Promise.resolve, then it will miss the `PONG` action dispatched immediately after the fork.

I'd stay away from promise based solutions as their async behavior can create subtle race effects in the cases like above. If you want to have a predictable behavior which can handle all edge cases use `actionChannel` instead.

**Comment by axelson** [comment]
Thanks for the detailed response! I'll keep that in mind for the workaround that I'm doing.

**Comment by totaldis** [comment]
I have a similar issue, from what I can tell, with the `put` and `take` logic. I have tracked it back to the jump from **0.10.0** -> **0.10.1**. I've checked **0.10.1** - **0.11.0** which all exhibit the same unexpected behavior that was otherwise working in **0.10.0**. I only recently found out because I rebuilt my local repo and upgraded some packages. 

I've setup my saga communication based entirely on actions. 
Watchers are built with this little helper function:
```js
const createWatcher = function(action, fn) {
  return function* () {
    while(true) {
      const { data } = yield take(action);
      yield fork(fn, data);
    }
  }
}
```
store setup
```js
  const sagaMiddleware = createSagaMiddleware();
  const store = createStore(reducer, initialState, applyMiddleware(sagaMiddleware));
  sagaMiddleware.run(sagas);
```
sagas
```js
function* s1() {
    console.log('s1 start');
    yield put({ type: 'S2_REQ' });
    console.log('after S2 put');
    yield take('S2_SUCCESS');
    console.log('after S2 success')
    yield put({ type: 'S1_SUCCESS'});
    console.log('s1 end');
}

function* s2() {
    console.log('s2 start');
    yield put({ type: 'S2_SUCCESS'});
    console.log('s2 end');
}

const watchS1 = createWatcher({ type: 'S1_REQ' }, s1);
const watchS2 = createWatcher({ type: 'S2_REQ' }, s2);

const sagas = [
  fork(watchS1),
  fork(watchS2),
];
```
**0.10.0** produces:
(index) s1 start
(index) s2 start
(index) after s2 put
(index) after s2 success
(index) s1 end
(index) s2 end

**0.11.0**
(index) s1 start
(index) s2 start
(index) s2 end
(index) after s2 put

**0.11.0** using `fork(()=>put)` trick in https://github.com/yelouafi/redux-saga/issues/336#issuecomment-220283929
(index): s1 start
(index): after s2 put
(index): s2 start
(index): after s2 success
(index): s1 end
(index): s2 end

Is this the expected behavior and I should migrate my code to using `actionChannel` per the comment above? It's hard to tell if this fits the same pattern as the other 3 issues on similar topics. 

I understand that async logic is not easy (especially in a single threaded language) so I'm happy with a response of "_you just shouldn't do it that way._"

**Comment by totaldis** [comment]
I think after re-reading https://github.com/yelouafi/redux-saga/issues/277#issuecomment-216083937 I understand the stack problem, and can get around it by adding a blocking call to the `s2` function:
```js
function* s2() {
    console.log('s2 start');
    yield call(()=>{});
    yield put({ type: 'S2_SUCCESS'});
    console.log('s2 end');
}
```
I'm still investigating if `actionChannels` will fit into my master plan, but at least I know now that the issue is aligned with @axelson's above
