### ISSUE TITLE
Composing actions

### ISSUE THREAD

**Issue by nhjk** [yelouafi/redux-saga#423]
With redux-thunk I can `dispatch(actionA).then(() => dispatch(actionB))`. For example, I have a form that I want to populate with initial values. Dispatching `actionA` allows me to get these initial values (by sending an async fetch). Dispatching `actionB` initializes the form with these values.

With sagas I can't do the above, because dispatches don't return promises. I have to create a new action - `actionAandB` - along with a new saga that combines the logic of `actionA` and `actionB`. Is there a more idiomatic way to do this instead of creating a new action, and a new saga for that action?

**Comment by slorber** [comment]
If your dispatch function returns promise, it's probably because you use some promise middleware.

It is possible to wait for promises in redux-saga, have you tried the following?

```javascript
const actionAPromise = yield put(actionA);
const actionAResult = yield actionAPromise;
const actionBPromise = yield put(actionB);
const actionBResult = yield actionBPromise;
```


I'm not sure if currently the put effect does return the result of the dispatch method however but you can try that.


Also, why do you want to mix redux-saga code with promise middleware? If you start to use sagas you would tend to dispatch only synchronous actions and manage effects inside sagas directly.

**Comment by nhjk** [comment]
My dispatches do not use promises, I am only using redux-saga for async middleware.

I have an action fetch a resource, for example a note. This action is `{ type: 'REQUEST_NOTE', id }`. I also have a form to edit notes. To populate the form with initial data I call an action creator with the signature `initialize(formName, initialData)`.

With redux-thunk I'd be able to chain these actions together like this `dispatch({ type: 'REQUEST_NOTE', id }).then(() => dispatch(initialize(noteForm, noteData))`. I don't have to create any new actions, I can compose the existing ones I have.

Because redux-saga does not return promises from dispatches the only solution I have been able to come up with is to create a new action, POPULATE_NOTE_FORM, with a new saga that contains this logic. I'm wondering if there is a more idiomatic way to do this.

**Comment by slorber** [comment]
@nhjk by default, neither redux or redux-thunk make dispatch({ type: 'REQUEST_NOTE', id }) returning a promise. So which middleware are you using that make it return a promise? 

Check for yourself: http://www.webpackbin.com/VJ406K4Ub

> Uncaught TypeError: store.dispatch(...).then is not a function


Also if redux-saga does not return promises from dispatches and it makes sense for your usecase, you can ask this feature to be added. It seems reasonable for me that the put effect does return the thing that gets returned by store.dispatch, no matter what it is.

**Comment by nhjk** [comment]
That was an error on my part, I should be dispatching an actionCreator not a plain action object. So it should be `dispatch(fetchNote(id)).then(() => dispatch(initialize(noteForm, noteData))`. With redux-saga, how do I combine these two actions together? Do I need to create a new saga every time I want to combine two or more actions?

**Comment by slorber** [comment]
So, you are dispatching promises, because fetchNote(id) is likely to return a promise. Thus please try what I have written above and if  this does not work open a feature request

**Comment by nbkhope** [comment]
Could you guys elaborate how to convert the following from `redux-thunk` to `redux-saga`?

Given a component that calls bound action creators like so:

```
componentDidMount() {
  this.props.fetchSomeData()
    .then(() => {
      const necessaryParameter = this.props.fetchedData; // this is defined after fetchSomeData() succeeds
      
      return this.props.fetchMoreInfo(necessaryParameter);
    });
}
```

In the example above, the bound action creator `fetchSomeData()` eventually dispatches a success action after making an http request, setting the `fetchedData` prop to a certain value. That value, in turn, is necessary for the call to the bound action creator `fetchMoreInfo()`.

I understand that we can do the above with `redux-saga` if we create a custom saga that performs both operations in sequence. My issue is, like the OP of this issue, how can we write it in a way that we don't need to create that custom saga? So it's like we already have two sagas that we may reuse and somehow combine FROM the component level, instead of the implementation of the sagas itself. Something like:

```
componentDidMount() {
  this.props.dispatchSomeActionThatCallsSagaA()
    .then(() => { // if successful
      this.props.dispatchAnotherActionThatCallsSagaBWithParameter(this.props.fetchedData);
    })
}
```
