### ISSUE TITLE
Issues with introduction text

### ISSUE THREAD

**Issue by jzaefferer** [yelouafi/redux-saga#436]
Someone recommended this project at a conference, but after reading the first few paragraphs of https://github.com/yelouafi/redux-saga#redux-saga I can't tell at all if this is really what I'm looking for.

I think that's mainly caused by the vocabulary used there. Both "thunks" and "saga" get used without any introduction, apparently assuming that the reader already knows what these are. I have no idea. Same for "Side Effects middleware" and "Asynchronous Actions". Accordingly, the rest doesn't make more sense either.

Looking for other introductions, I found the beginner tutorial, but that isn't a good replacement to understand what this is even about. The other Introduction article (Background on the saga concept) links to a video and a scientific paper (of course a PDF). That doesn't work for me either.

I'm sure there's lots of interesting ideas here, they just need to be a bit more accessible...

**Comment by slorber** [comment]
Hi @jzaefferer 

You may find my answer here easier to understand:
http://stackoverflow.com/questions/34570758/why-do-we-need-middleware-for-async-flow-in-redux/34623840#34623840

**Comment by jzaefferer** [comment]
Not really, since it also uses a lot of vocabulary that I'm not familiar with. While I've read plenty of FP articles trying to explain monads, it never "clicked", so using that to explain redux-saga isn't helping. Same for "thunk", except that I only heard this term for the first time a few days ago.

I'm coming from an application that uses React, react-router and Ampersand models and collections. I have some problems in managing data in that architecture, and redux-saga was recommended to me to solve some of those problems. I still can't tell if it does.

**Comment by slorber** [comment]
@jzaefferer if you don't involve time to understand underlying concepts it's hard to explain you redux-saga in the first place. It is not the typical library that beginners should start with. Plus the redux-saga project is not mature yet so the documentation can probably be made better over time.


This is a thunk, in the context of Redux:

```javascript
const userId = "123"

// Create a thunk (task usually done inside a Flux actionCreator)
const thunk = dispatch => fetch(`http://data.com/${userId}`)
    .then(res => res.json())
    .then(
      data => dispatch({ type: 'USER_PROFILE_LOADED', data }),
      err => dispatch({ type: 'USER_PROFILE_LOAD_FAILED', err })
    );

// You can dispatch a thunk
reduxStore.dispatch(thunk);
```


A thunk is not something complicated, and it's well-explained on the page I gave you. If you already use Redux, you must know what a thunk is. If you don't use redux, redux-saga has probably no utility to you, so maybe start first by learning Redux in the first place.

Please take a look at these tutorials: 
- https://egghead.io/courses/getting-started-with-redux
- https://egghead.io/courses/building-react-applications-with-idiomatic-redux


These are the best tutorials to Redux you can find out. It will explain thunks. Don't use redux-saga if you don't understand the limited possibilities of redux-thunk. Don't use Redux if you don't see the limited possibilities of React or Flux. Don't use a library if you don't yet understand the problem it tries to solve.

**Comment by jzaefferer** [comment]
> It is not the typical library that beginners should start with

Then who is it for? The current introduction doesn't tell.

> Don't use a library if you don't yet understand the problem it tries to solve.

That was the point of this ticket. The current explanation is inaccessible to me (and I guess anyone else not already deeply familiar with related concepts). It doesn't have to be.

> A thunk is not something complicated, and it's well-explained on the page I gave you

That's not helping. If you tell me something is easy or not complicated and I don't understand, it makes me feel stupid. That's not the goal, right?

> It is just a syntactic sugar that is equivalent to:

"just" is a toxic word in the context of documentation, same as "easy", "simple" or "straightforward".

**Comment by slorber** [comment]
@jzaefferer I'm sorry if I feel rude and make you feel dumb, it's not the point of my comment.
I understand that you might not understand thunks better after my comment, and don't say you are stupid if you don't. But you certainly will once you have watched the Egghead videos.

We all agree most people have hard time to understand sagas in the first place, because the doc is not perfect for beginners, because the saga pattern is new to most frontend developers, because we maybe should have called the pattern "process manager", and because redux-saga is using cutting edge technologies as implementation details, like ES6 generators and Redux.

I'll try to explain in a simple way.

# Saga with Vanilla JS and an event bus

The simplest explanation of what a saga is basically: "a process that receive events, and may emit new events (sync or async)". 

This saga will handle the fetching of a user profile data, whenever an username is clicked into your system.

```javascript
const {emit,subscribe} = SomeEventBusSystem;

function setupUsernameClickedSaga() {
   subscribe(function(event) {
      if ( event.name = "USERNAME_CLICKED ) {
         fetch(`http://data.com/${event.userId}`)
            .then(res => res.json())
            .then(
              data => emit({ type: 'USER_PROFILE_LOADED', data }),
              err => emit({ type: 'USER_PROFILE_LOAD_FAILED', err })
             );
      }
   });
}
```

As you can see, it the concept is quite simple to understand with VanillaJS. I hope you don't mind if I say it's easy, because it really is. You can use this pattern on top of any JS framework you want as long as you have some kind of event bus from which to listen to and to emit new events.

# Vanilla JS Saga benefits

Once you know what is a saga is, you can understand why it's useful. In this case it permits to handle asynchronous operations (talking to your API), and it permits to avoid polluting your view component with imperative logic (`e => fetchUserProfile(id)`), which permits to decouple the components and make them more reusable (but also more complex).

Now, you can reuse the view component in another context, and maybe in this context a click on the username does not mean that we should load the user profile but something else, like opening chat window with the user instead).

A saga is not suited for simple apps, because it makes the app more complex. But more manageable at large scale, particularly if you want to dispatch the work across multiple teams.



# More powerful sagas with Redux-saga

Redux-saga is an implementation of sagas on top of Redux (it actually is not that much coupled with Redux and can be used on top of other event systems).

The complexity of Redux-saga is related to the expression of sagas with generators, which mean you need some understanding of what a generator is in the first place, but the concept behind it remains the same.

The usage of generators give us an expressive way to describe complex concurrency patterns that is not easy to handle with VanillaJS, and the declarative effects approach it uses makes it easy to test, compared to my initial Vanilla JS saga implementation which requires complex mocking strategies.


# Conclusion

I hope you understand what a saga is and you see the value of using this pattern.
If you don't, you are not an idiot. Maybe it will make sense once you really try to use the pattern on a complex app (Redux or not).

If you want to use Redux-saga for real, I still recommend that you understand the prerequisites (Redux and ES6 generators). Having worked with thunks is not a prerequisive but will give you some insights on why sagas are nice

**Comment by jzaefferer** [comment]
> What do you think about this? Specifically @jzaefferer, does this explain the idea better maybe? [...]
> This first introduces the solution and the problem, explains the mental model, explains the assumed technical familiarity and then compares it to redux-thunk for those who have used it, but doesn't necessitate the understanding of thunks or anything.

Yes, that sounds/reads a lot better to me.

**Comment by mxstbr** [comment]
Submitted a PR for further discussions: #437.

I don't expect it to be merged straight away, but it should be enough to kick off some exploration hopefully!

**Comment by yelouafi** [comment]
@mxstbr I find your introduction better

I'm not particularly proud of the current Section on Sagas; Either we should put content related to how Sagas work in the context of frontend/React apps, giving example with redux-saga; or at the very least we should put the links in the resources section. The point is that people are not required to go through the academic papers or backend specific content to start using the library.

**Comment by mxstbr** [comment]
Thanks @yelouafi, if you have any comments I'll gladly update the PR so we can get a better introduction out!

> I'm not particularly proud of the current Section on Sagas; Either we should put content related to how Sagas work in the context of frontend/React apps, giving example with redux-saga; or at the very least we should put the links in the resources section. The point is that people are not required to go through the academic papers or backend specific content to start using the library.

I agree, let's take a look at that in a separate issue/PR?

**Comment by yelouafi** [comment]
closing this. see #437
