### ISSUE TITLE
Dealing with fetch/promise

### ISSUE THREAD

**Issue by rpmonteiro** [yelouafi/redux-saga#510]
Hi guys, for the life of me I can't figure out how to deal with this API request...

![image](https://cloud.githubusercontent.com/assets/7824615/18080683/696a293c-6e8e-11e6-8d7a-58aa2c0328fa.png)

I've tried returning the fetch instead of yielding, but then I get a promise in return, and the `yield call` doesn't wait for it to resolve...

I know I'm being a doofus for sure, but does anyone care to give me a little hand?

Thank you very much!!

**Comment by rpmonteiro** [comment]
Solved it by having the function containing the fetch be a non-generator function.

![image](https://cloud.githubusercontent.com/assets/7824615/18084366/e2d92fe2-6e9e-11e6-8beb-5783dacef17a.png)

Why that is? Beats me...

Can someone chime in as to why it doesn't work if you return a fetch inside a generator?

**Comment by Andarist** [comment]
Hey, I was just correcting your example when you have solved it by yourself ;)

You could do it also like this:

```
function* fetchVersion(id) {
	const token = yield select(getUsetToken)
	const url = `${settings.apiServer}/version/${id}`
	const options = {
		method: 'get',
		headers: {
			Authorization: 	`Bearer ${token}`,
			Accept: 		'application/json',
			'Content-Type': 'application/json',
		}
	}

	const fetchRes = yield fetch(url, options)
		.then(checkHttpStatus)
		.then(parseJSON)
		.catch(err => ({err}))
		.then(res => ({res}))

	return fetchRes
}

export function* loadVersionFlow() {
	while (true) {
		const { data } = yield take(ITEM_VERSION_REQUEST)
		const id = parseInt(data)
		const { err, res } = yield call(fetchVersion, id)
		console.log(err, res)
	}
}

```

or even better - instead of `const fetchRes = yield fetch(url, options)` you could wrap this whole fetch into a function and just use `const fetchRes = yield call(fetchFn, url, options)`

Gonna write some explanation in few minutes

**Comment by slorber** [comment]
In the first version, you don't return the fetch, so the generator call does not return anything, it just blocks for the fetch result and does not return anything to the caller generator. Blocking and waiting for result in fetchVersion does not mean it will be returned. Because in fetchVersion you could have waited for multiple promises and the generator could not know which one of the results to return.

Btw not sure it's really useful to use a generator here: just returning a promise like you did in 2nd attempt is perfectly fine and simpler if you don't need to use take/put/select inside fetchVersion it's not worthy to use a generator.

**Comment by rpmonteiro** [comment]
Thank you @slorber and @Andarist !! Great explanations there!
Have a nice day both of you 😄
