### ISSUE TITLE
Is put non-blocking?

### ISSUE THREAD

**Issue by granmoe** [yelouafi/redux-saga#604]
I have some code like this:

```
function* mainSaga () {
  yield takeLatest('some-action', function* () {
    yield put({ type: 'trigger-async-calls' })
    yield call(api.thirdCall)
  })
}

function* anotherSaga () {
  while (yield take('trigger-async-calls') {
    yield put({ type: 'trigger-saga-a' })
  }
}

function* sagaA () {
  yield takeLatest('trigger-saga-a', function* () {
    yield call(api.firstCall)
    yield call(api.secondCall)
  }
}
```

When I dispatch `'some-action'`, `api.thirdCall` goes out first. I expected to see `api.firstCall` then `api.secondCall` then `api.thirdCall` after everything triggered by the `put`s had been settled. What am I doing wrong? Or am I misunderstanding how saga handles this? I would like to be able to have my outermost saga (`mainSaga` here) use takeLatest so it can be arbitrarily cancelled/restarted, and same with `sagaA`, and still get my desired behavior of having `api.firstCall` happen first, then `api.secondCall` then `api.thirdCall`. The only thing I can think of that might be throwing this off is that `sagaA` uses `takeLatest` which forks the processes. Maybe this is causing control to return to `mainSaga` before the first and second calls happen?

**Comment by arashd** [comment]
I'm not sure if I'm understanding correctly. Maybe I'm missing what you're trying to achieve since this is a barebones example. `put` simply dispatches and then immediately gives back control. So `api.thirdCall` gets called right away. You should be able to achieve the same by simply doing: 

```
function* mainSaga () {
  yield takeLatest('some-action', function* () {
    yield call(anotherSaga)
    yield call(api.thirdCall)
  })
}

function* anotherSaga () {
    yield call(sagaA)
}

function* sagaA () {
    yield call(api.firstCall)
    yield call(api.secondCall)
}
```

You could also use `yield*` but it would make testing less pleasant. In this case, if you cancel mainSaga, the cancellation propagates downward and all the sagas get cancelled.

**Comment by granmoe** [comment]
Oh, OK, so `put` is meant to be give back control immediately in all cases?

I can't do what exactly what you suggest due to other requirements of the app, but this clears things up completely. I had assumed that if a `put` triggers other sagas, those sagas will be settled before control is returned to the saga that called `put`.

**Comment by Andarist** [comment]
The case is kinda tricky, I'll try to explain what's happening and why. `put` is kinda 'synchronously' blocking. 

What I mean by that that its not just a simple wrapper around `dispatch`. Its effect runner (the function executing `put` effect) is wrapping a function making a dispatch in `asap` queue. `asap` can handle 2 scenarios: 

1. If queue is suspended its pushing a task (dispatching one) to the end of the queue and the queue will get executed when `flush`ed
2. If queue is not suspended its suspending it immediately, adding to the queue AND `flush`. So the queued task is the first to happen (action dispatched etc). But if this dispatched action now triggers some `take`s during being emitted to the `redux-saga` and other `put`s come into play because of that they will meet the 1st scenario, cause this 1st put has suspended the queue, but as they get pushed to the queue they will be executed by the same `flush`ing loop. `isSuspending` lock is lifted on the end of the `flush`, when all queued tasks finish.

That being said, once a task *is* executed it will resume effectively `dispatch` and resume your saga.

However you are meeting the other `asap` fatigue. `takeLatest` is consisted of such logical steps:
1. `yield take(pattern)` - 'take(some-action)' here
2. when action is taken it checks if there is already a previous task, if it is - `yield cancel(prevTask)`
3. `prevTask = yield fork(worker)`, go back to the 1st step

While looking at the `fork` effect runner we could see such thing
```
asap.suspend()
const task = proc(taskIterator, subscribe, dispatch, getState, options, effectId, fn.name, (detached ? null : noop))
// ...
asap.flush()
```

Effectively that's what happening in your case:
1. running `fork`, cause of your `takeLatest`
2. therefore suspending the `asap`
3. running your worker, geting to `yield put({ type: 'trigger-async-calls' })`
4. executing this `put`, trying to `asap` dispatching, but as its suspended, its geting to the `queue` instead of dispatching right away
5. geting to the `asap.flush()`, executing the queued `dispatch({ type: 'trigger-async-calls' })`
6. the action is emitted back to the saga by the middleware where there is already a listener waiting for it (`take('trigger-async-calls')`)
7. resuming that generator and meeting `yield put({ type: 'trigger-saga-a' })`, trying to asap it, but we are in the middle of the flush (step 5), so its queued up
8. finishing dispatching `trigger-async-calls` (step 5) so resuming your worker and hence `api.thirdCall` happens
9. `flush` geting next item from the queue - and therefore dispatching your `trigger-saga-a` now

**Comment by granmoe** [comment]
Wow! Thank you for the detailed explanation :-) 👍 👍 👍 

I decided to just `yield put` a success action at the end of `sagaA` and `yield take` it right after the `put` in `mainSaga`. I'm going to have to read your reply a few times to fully understand it.

Thanks again :-)

**Comment by Andarist** [comment]
Well, truth to be told - i dont even even know if its 100% correct and if
it holds up in the future. Scheduling is a really complex situation and it
needs to be addressed accordingly
