### ISSUE TITLE
How to check if channel is empty?

### ISSUE THREAD

**Issue by bstro** [yelouafi/redux-saga#606]
What's the best way to determine if a channel is currently empty? The `Buffer` interface seems to describe an `isEmpty` method. But how do I get at the underlying buffer from a channel?

**Comment by Andarist** [comment]
Just yield flush(channel)

On Sat, 29 Oct 2016 at 00:19, Brendan Stromberger <notifications@github.com>
wrote:

What's the best way to determine if a channel is currently empty? The Buffer
interface seems to describe an isEmpty method. But how do I get at the
underlying buffer from a channel?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/yelouafi/redux-saga/issues/606>, or mute the thread

**Comment by bstro** [comment]
Thanks for the reply @Andarist; for my use case, I just need to know if the channel _is empty_, but not actually empty it.

**Comment by Andarist** [comment]
Well, you can always pass a buffer manually, so you have reference to it and you can check its `isEmpty` method

```
import { buffers } from 'redux-saga'
import { actionChannel } from 'redux-saga/effects'
// ...
function* saga() {
  const buffer = buffers.fixed() // or some other buffer type
  const chan = yield actionChannel('ACTION_TYPE', buffer)

  // ...
  if (buffer.isEmpty()) {
     //...  
  }
}
```

**Comment by bstro** [comment]
Perfect. Thanks!!
