### ISSUE TITLE
Reject action catched by take

### ISSUE THREAD

**Issue by vanhtuan0409** [yelouafi/redux-saga#612]
When I inspect the real-workd example, I see that redux-saga can check the cached before it decide whether to make an api call or not
But the problem is, if the data already cached and we did not make any api call, the action ```LOAD_REPO``` is still fired
Is there any way that we can cancel or reject the ```LOAD_REPO``` action and dont let it get to stored? Some of my reducer is listen to that action to display the loading spinner
Also I check the ```takeLatest``` util, even though it do cancel the pending task. It still allow 2 action to pass by and get to the store

```
// load repo unless it is cached
function* loadRepo(fullName, requiredFields) {
  const repo = yield select(getRepo, fullName)
  if (!repo || requiredFields.some(key => !repo.hasOwnProperty(key)))
    yield call(fetchRepo, fullName)
}
// Fetches data for a Repo: repo data + repo stargazers
function* watchLoadRepo {
  while(true) {
    const {fullName, requiredFields = []} = yield take(actions.LOAD_REPO)

    yield fork(loadRepo, fullName, requiredFields)
  }
}
```

**Comment by Andarist** [comment]
`redux-saga` only listens for actions (and can dispatch too ofc). It has no power to control if the taken action hits reducers or not. If you need to separate those you need to split the action into 2. It would look smth like this:
```javascript
// load repo unless it is cached
function* loadRepo(fullName, requiredFields) {
  const repo = yield select(getRepo, fullName)
  if (!repo || requiredFields.some(key => !repo.hasOwnProperty(key)))
    yield put({ type: 'FETCH_REPO' }) // just listen for FETCH_REPO in your reducers, so it only shows the spinner while truly downloading data from the server
    yield call(fetchRepo, fullName)
}
// Fetches data for a Repo: repo data + repo stargazers
function* watchLoadRepo {
  while(true) {
    const {fullName, requiredFields = []} = yield take(actions.LOAD_REPO) // do not listen on LOAD_REPO in reducers
    yield fork(loadRepo, fullName, requiredFields)
  }
}
```

**Comment by vanhtuan0409** [comment]
I agree that could be 1 solution
But it feel a little bit un-natural to come up with a new Action only for redux-saga to listen to
A api call flow should normally consist of 3 action
+ REQUEST (fired by client side)
+ SUCCESS (fired after received the respose)
+ FAILURE (fired after api call error)

**Comment by Andarist** [comment]
Well, as I said - saga acts as a listener for dispatched actions and it wont prevent them from happening. What I've mentioned is a proposed solution, you could do bunch of other stuff to deal with it, but it depends on how *you* want to handle it, what *you* feel is the best for your project etc. There is no ultimate solution here, but I guess splitting action into 2 is the most straghtforward and recommended one (but ofc not enforced), you could maybe just name them differently - instead of `yield put({ type: 'FETCH_REPO' })` for example `yield put({ type: 'SHOW_SPINNER' })`

**Comment by Andarist** [comment]
Check out related issue - https://github.com/yelouafi/redux-saga/issues/307#issuecomment-217197011 . Ofc do not hesitate to ask additional questions.

**Comment by slorber** [comment]
@vanhtuan0409 instead of emitting a LOAD_REPO event, you can emit LOAD_REPO_REQUESTED

Then you have a saga, that will decide weither or not to fire a LOAD_REPO

I think this is what @Andarist proposed as well and it does not seem unnatural to me at all. 
What feels unnatural is to dispatch a LOAD_REPO action, and to expect that in some cases it does not lead to any loading at all :)

Maybe you can take inspiration from this notification system I've build, which use a similar pattern:

http://stackoverflow.com/a/38574266/82609

**Comment by vanhtuan0409** [comment]
I got it 👍 
It end up i modified my solution a little bit to fit the situattion
