### ISSUE TITLE
Handle promise response and event callback together

### ISSUE THREAD

**Issue by dimapaloskin** [yelouafi/redux-saga#613]
Imagine that there is next function:

```js
function asyncTask(callback) {
  return new Promise((resolve, reject) => {

    if (callback) {
      setTimeout(() => {
        callback(50);
      }, 100);

      setTimeout(() => {
        callback(80);
      }, 200);
    }

    setTimeout(() => {
      resolve('result');
    }, 500);
  });
}
```
It's similar with axios workflow when I need upload file and catch progress event.
How I can get the promise result and also handle progress event?
For example something like that:

```js

function* uploadSource(action) {

  const result = yield call(asyncTask, (data) => {
    put({ type: 'PROGRESS', payload: data });
  });
  put({ type: 'SUCCESS', payload: result });
}
```

Sure, last code example is not working. I tried use the eventChannel, but without any success result.

**Comment by Andarist** [comment]
Well, such thing could be achieved with `eventChannel` as you have mentioned and it would look smth like that
```javascript
const identity = (a) => a

const createAsync = () => {
	let emit
	const chan = eventChannel(emitter => {
		emit = emitter
		return () => {}
	})
	const promise = new Promise((resolve, reject) => {
		setTimeout(() => emit(50), 100)
		setTimeout(() => emit(80), 200)
		setTimeout(() => {
			resolve('result')
			emit(END)
		}, 500)
	})

	return [ promise, chan ]
}

function* watchOnProgress(chan) {
	while (true) {
		const data = yield take(chan)
		yield put({ type: 'PROGRESS', payload: data })
	}
}

function* uploadSource(action) {
	const [ promise, chan ] = createAsync()
	yield fork(watchOnProgress, chan)
	const result = yield call(identity(promise))
	yield put({ type: 'SUCCESS', payload: result })
}

```

I realise that its not the cleanest solution with the exposing of `emit` outside of the callback so promise can utilize it, but its what I've come up with for now.

**Comment by dimapaloskin** [comment]
@Andarist thank you, it's help. But I added few changes.
For now it's looks like:

```js

function asyncTask(callback) {

  if (callback) {
    setTimeout(() => {
      callback('progress');
    }, 300);
  }

  return new Promise((resolve) => {
    setTimeout(() => {
      resolve('finish');
    }, 500);
  });
}

function createAsyncTaskRunner(data) {

  let emit;
  const chan = eventChannel(emitter => {
      emit = emitter
      return () => {}
  });

  const promise = asyncTask((data) => {
    emit('PROGRESS');
    /*
       stop if 100% uploaded (using inside project) 
       if (data && data.progress === 1) {
        emit(END);
      }
    */
  });


  return [ promise, chan ];
}


function* watchOnProgress(chan) {
  while (true) {
      const data = yield take(chan);
      yield put({ type: 'PROGRESS', payload: data });
  }
}

function* uploadSource(action) {
  const [ promise, chan ] = createAsyncTaskRunner('test');
  yield fork(watchOnProgress, chan);
  try {
    const result = yield call(() => promise);
    put({ type: 'SUCCESS', result });
  } catch (err) {
    put({ type: 'ERROR' });
  }
}
``` 

Thanks a lot!

**Comment by slorber** [comment]
@Andarist for me your solution is fine, I was about to suggest something very similar. Maybe it could be simpler to just return a chan and have an end event signaling that the upload did complete, maybe with a status? Seems to me that there's a little intersection in functionality between using both a stream + a promise, and that just a stream would be enough.


Another problem is that for the saga to kick in it generally has to wait for a UPLOAD_STARTED event, and handling that inside a saga means that user is likely to pass unserializable content inside a Redux action, which is not a very good idea in the first place.

For such case, I'd rather use a thunk, or a RxJS-based middleware so that it does not require putting File / Dom events directly inside the sagas

**Comment by slorber** [comment]
@Andarist for me your solution is fine, I was about to suggest something very similar. Maybe it could be simpler to just return a chan and have an end event signaling that the upload did complete, maybe with a status? Seems to me that there's a little intersection in functionality between using both a stream + a promise, and that just a stream would be enough.


Another problem is that for the saga to kick in it generally has to wait for a UPLOAD_STARTED event, and handling that inside a saga means that user is likely to pass unserializable content inside a Redux action, which is not a very good idea in the first place.

For such case, I'd rather use a thunk, or a RxJS-based middleware so that it does not require putting File / Dom events directly inside the sagas

**Comment by ASHISH932** [comment]
I tried using above mentioned approach but it is not working. I am using ReadableStream of fetch body, and is unable to create eventChannel from there. Is there any other approach in redux-saga or custom middleware would be a better option?

**Comment by jackkkkkkkkkkkkk** [comment]
i tried above solutions.both doesnt work is any other solution ?
