### ISSUE TITLE
Await for multiples take

### ISSUE THREAD

**Issue by sospedra** [yelouafi/redux-saga#643]
Imagine we want to call two async endpoints from our API. And we need **both of them done before** `put` the success action.

So, I tried something like this (and quite a lot of different ways):

*Note: the following is a lazy implementation*
```js
const fetchMultiple = function * () {
  // we have a CALL_API saga for the request
  // which ends by putting a new action with the request payload
  yield put(callApi('foo'))
  yield put(callApi('bar'))

  // the following code is wrong
  // yield take is not iterable but if we assign it to a single var
  // it'll take only the first to be triggered
  const [foo, bar] = yield take([
    FETCH_FOO,
    FETCH_BAR
  ])

  yield put(fetchMultipleSuccess(foo, bar))
}

export default function * () {
  yield takeLatest(FETCH, fetchMultiple)
}
```

But the `yield take([])` works by `OR` operator instead of `AND` which would be the needed here.
Is there any solution for this? Am I approaching the issue in a wrong way?

Many thanks

**Comment by Andarist** [comment]
Try yield [take(FETCH_FOO), take(FETCH_BAR)]

**Comment by sospedra** [comment]
I tried what you mentioned @Andarist and also this approach: https://github.com/yelouafi/redux-saga/issues/212

And none of those worked :( It just stays bloqued forever.

**Comment by Andarist** [comment]
Could you post a webpackbin with your code? It should certainly work if you yield an array of effects. Im using this pattern in my project without any issues.

**Comment by sospedra** [comment]
Here it goes @Andarist 

http://www.webpackbin.com/VJjnG8FbG

**Comment by Andarist** [comment]
Ok, so there were some issues with your code. All effects (what you import from `redux-saga/effects`) - `take`, `put`, `fork` etc are effect creators, basically just functions which return objects with certain structure. And those objects can be later interpreted by the `redux-saga` in order to execute them. So such thing like this wont work
```javascript
const asyncFn = setTimeout((type, sec) => {
  put({ type, sec })
}, sec * 1000)
```
it simply creates `put` effect/object but it cannot pass it to the saga which could interpet it and dispatch the action as the outcome. The only way to pass effects to the saga is by `yield`ing them (those effects/objects) from the generator which is controlled by the `redux-saga`

Here you go with the corrected code - http://www.webpackbin.com/E1SqxwKZz

**Comment by sospedra** [comment]
You're right @Andarist . Thanks for the help. This was one of the troubles I had. The other one was... Well, I need to keep in mind that the spread operator in an actions is dangerous... Specially if the payload contains a `type` attribute, if you know what I mean >.<
