### ISSUE TITLE
Different ways to watch actions

### ISSUE THREAD

**Issue by schuchowsky** [yelouafi/redux-saga#684]
Hello guys, while reading the documentation and tutorials, I see different ways to watch actions and trigger sagas:

*While take*
```javascript
function* watchTodos() {
  while (yield take('FETCH_TODOS')) {
    yield fork(loadTodos);
  }
}
```

*While true*
```javascript
function* watchFetch() {
  while (true) {
    yield take(FETCH_POSTS)
    yield call(fetchPosts)
  }
}
```

And I am, particularly, using this syntax:
```javascript
export default function* watchFiles() {
  yield [
    takeEvery('DELETE_FILE', deleteFile),
    takeEvery('LIST_FILES', listFiles),
  ]
}
```

So, my doubt is that I don't understand the need of having that while(true) loop, if we have `takeEvery` function. Am I going to miss something using my approach?

**Comment by kuy** [comment]
@schuchowsky  First, I'd like to explain a difference between `while(true)` and `while(yield take(...))`. If you don't need to use an action that is yielded from `take` effect, you may use `while(yield take(...))` pattern. If you want to use an action, please use `while(true)` with `var action = yield take(...)`.

> So, my doubt is that I don't understand the need of having that while(true) loop, if we have takeEvery function.

Yes, you're right. But sometimes I feel it's overkill to always use `takeEvery` instead of while loop in small sagas.

**Comment by schuchowsky** [comment]
@kuy Oh I see... so in the example above, the `while(true)` could be replaced by `while (yield take (FETCH_POSTS)`, because the function yielded from take effect is not being used in that case, right?

Overkill? Hm... What would be the correct use for it then? 

I feel like it's more readable using `takeEvery` because in one function I declare all my watchers.

**Comment by kuy** [comment]
> the while(true) could be replaced by while (yield take (FETCH_POSTS), because the function yielded from take effect is not being used in that case, right?

Yes!

> Overkill? Hm... What would be the correct use for takeEvery then?

To use `takeEvery`, you need to split a saga. This is what I feel it's overkill for small sagas. For example, I use `takeEvery` to avoid dropping dispatched action.

```js
function* watchFetch() {
  while (true) {
    yield take(FETCH_POSTS)
    yield call(fetchPosts)
  }
}
```

This code will work well **only if** `fetchPosts` function returns quickly **and** `FETCH_POSTS` actions are not dispatched frequently. If next`FETCH_POSTS` action is dispatched before calling of `fetchPosts` returns, it will lost (drop) `FETCH_POSTS` action. Since `takeEvery` = `take` + `fork`, dropping actions will not be occured in `takeEvery`. You can also avoid this issue by `actionChannel`.

> I feel like it's more readable using takeEvery because in one function I declare all my watchers.

It depends on a case you're facing. I would like to say that always using `takeEvery` is not wrong. If you don't feel splitting a saga is boring, it's not a problem 😃

**Comment by Andarist** [comment]
@kuy 
> To use `takeEvery`, you need to split a saga.

What do you mean by splitting?

> This code will work well only if fetchPosts function returns quickly and FETCH_POSTS actions are not dispatched frequently. If nextFETCH_POSTS action is dispatched before calling of fetchPosts returns, it will lost (drop) FETCH_POSTS action.

Well, sometimes that is exactly what you are trying to achieve, so it really all depends on requirements. Sometimes deliberately calling `call` to block a `while (true)` loop until `call` is resolved is what is needed by the app.

@schuchowsky 
> So, my doubt is that I don't understand the need of having that while(true) loop, if we have takeEvery function. Am I going to miss something using my approach?

Well, those examples in the docs are for presentation purposes. `takeEvery` is not always sufficient as its just a helper creating for you something similar to this:
```javascript
function* watchFetch() {
  while (true) {
    const action = yield take(FETCH_POSTS)
    yield fork(fetchPosts, action)
  }
}
```

But having ability to use take manually in while loops allow you to model more complex scenarios, this one is so trivial that it makes sense to have a shortcut form - `takeEvery`

**Comment by schuchowsky** [comment]
Ok guys! Now it's much clearer for me. I liked the term `drop` actions btw.

Thank you very much @Andarist @kuy.

**Comment by HARINANDHAN** [comment]
guys I have question how do I register multiple sagas for same action ?
