### ISSUE TITLE
How to put() within a callback?

### ISSUE THREAD

**Issue by bgerm** [yelouafi/redux-saga#79]
There have been a few instances where I've wanted to `put` within a callback to realize that the action never gets reduced on.  Is it possible to do the following with sagas?

```javascript
function* hideNotification() {
  let clearTimer = null;
  const { SET_NOTIFICATION, CLEAR_NOTIFICATION } = NotificationActions.actionTypes;

  while(true) {
    const action = yield take([SET_NOTIFICATION, CLEAR_NOTIFICATION]);
    if (clearTimer) {
      clearTimeout(clearTimer);
      clearTimer = null; 
    }
    
    if (action.type === SET_NOTIFICATION) {
      clearTimer = setTimeout(() => put(NotificationActions.clearNotification()), 300);
    }
  }
}
```

**Comment by slorber** [comment]
Not sure what you want to do but it seems what you want is:
- after a notification gets set, it gets cleared after 300ms
- if a new notification gets set but the old one is not cleared yet, then the old timer should not mess up with the new notification


Maybe something like this will work fine:

```javascript
function* hideNotification() {
  while(true) {
    const {action, wait} = yield race({
        action : yield take(SET_NOTIFICATION);
        wait : call(wait, 300);
    });
    if ( !action ) {
        yield put(NotificationActions.clearNotification()
    }
  }
}
```

**Comment by bgerm** [comment]
Thanks for the reply, @slorber.  I wound up using task cancellation to achieve the same thing.  You pointed me in a just-do-it-another-way direction.

**Comment by aft-luke** [comment]
I have the same question pointed out by @bgerm, but here's a different scenario where a callback might be convenient to have: dialogs. If I want a generic dialog service, I would like to just say "open the dialog, use this view, use this model, use these callbacks when the dialog is closed/confirmed/cancelled" instead of having to repeat myself for different dialogs throughout an app.

```
function* listener() {
    yield take(OPEN_DIALOG)

    // notify the dialog service
    yield put({ 
        type: 'CREATE_DIALOG'
        , onConfirm: specialPut({ type: 'CONFIRM' })
        , onCancel: specialPut({ type: 'CANCEL' })
        , model: { ... }
    })

    // wait for close or confirm
    yield race({
       cancel: take(CANCEL)
       , confirm: take(CONFIRM) 
    }) 

   ....
}

// this doesn't work for a variety of reasons
// 1) coroutine belongs to another lib and is promise based; redux saga doesn't handle promises
// 2) even with an adapter that allows for resolving non-promise values, the put never seems
// to resolve... the EFFECT_TRIGGERED shows up in dev tools, but never `EFFECT_RESOLVE`
function specialPut(action) {
    return Promise.coroutine(function* putter() {
        yield io.put(action)
    })
}

// this does seem to work but is also heavy-handed
function aDifferentPut(action) {
  return function() {
    runSaga(function* putter() {
      yield put(action)
    }())
  }
}
```

**Comment by slorber** [comment]
@aft-luke what you want to achieve seems a bit far-fetched. Instead of trying to abstract over redux-saga you could simply create a reusable React component that you customize in different places.

An idiomatic way of using Redux is to keep a serializable event log. In means you are not supposed to dispatch actions with callbacks, generators, functions, promises or observables as payload. 

It is also my personal opinion (not really followed by the rest of the community atm) that the dispatched actions should always represent something that HAS happened (past tense) and not be used to do remove procedure calls. This is how event-sourcing works in the first place.

You can see how I remove, with redux-saga, an idiomatic redux-thunk rpc call here by a simple event dispatch: http://stackoverflow.com/a/34623840/82609

Flux/Redux is heavily close to event-sourcing, but a lot of confusion comes from the word "action" because people now think the "dispatcher" is supposed to dispatch both commands (rpc / user intent) and events (descriptors of what happened).

**Comment by aft-luke** [comment]
Thanks for the input @slorber . This issue is probably not the best place to discuss, but here it goes anyways. 

Having used redux for a few months now across a large project, my biggest pain point is the reusability/composability of components. I think the mentioned use case is another example. 

App-level architecture flows relatively naturally, but building a single encapsulated unit is really difficult. I feel like it's too simple for the "api surface" of a redux app to grow very large, and that makes refactors or redesigns rather difficult. 

For example, if I have a component concerned with `EVENT_HAPPENED`, and that component is made up of a handful of reducers (each managing a relatively complex unit of state), do I pipe `EVENT_HAPPENED` from the root of the component all the way down the reducer hierarchy? Do I translate `EVENT_HAPPENED` in the root to an internal API call? In the former case it feels like I'm pouring concrete, and the latter case results in a lot of boilerplate.

A domain driven design approach would translate any event that is external to the component's domain into an internal representation, at which point the root of the reducer hierarchy becomes an `aggregate root`. This, unfortunately, means a very large reducer at the top of the hierarchy that must capture and translate every single event used by any component below. 

```
function rootComponentReducer(state, action) {
    switch (action.type) {
        case 'child_a_1':
            childAReducer(state, { type: 'internal_a_1' })
            ...
        case 'child_a_2':
            childAReducer(state, { type: 'internal_a_2' })
            ...
        case 'child_b_1':
            childBReducer(state, { type: 'internal_b_1' })
            ...
        case 'child_b_2':
            childBReducer(state, { type: 'internal_b_2' })
            ...
            ...
            ...
        case 'child_z_2':
            ...

    }
}
```

On one hand this is a very explicit contract between a component and the rest of the world (good), but on the other it results in an enormous reducer (bad) where a lot of the `capture world event -> translate aggregate event` is duplicated effort that grows with the number of reusable components nested inside a particular root.

I would be interested in your thoughts on this. Maybe I'm coming at it from the wrong angle?

I agree with you that this is (mostly) classical event sourcing. I haven't been very disciplined about maintaining "has happened" events and have fallen into the "action trap" which may be at the root of some issues I'm having.

**Comment by aft-luke** [comment]
For those interested, here's a not-great solution to "how do I put from a callback". It's not great because this really isn't the way things should be structured, as @slorber mentions above.

```javascript
// because of the way "call" works, if we want to "put" an action
// after a callback is invoked, we can return a promise that is
// bound to resolve when the callback is invoked
function bindCallbackToPromise() {
    let _resolve
    const promise = () => {
        return new Promise((resolve) => {
            _resolve = resolve
        })
    }
    const cb = (args) => _resolve(args)

    return {
        promise
        , cb
    }
}

function* watchForDialog() {
    yield take(DIALOG_REQUESTED)

    const cancel = bindCallbackToPromise()
    const confirm = bindCallbackToPromise()

    yield put({
        type: DIALOG_OPENED
        , cancel: call(cancel.cb)
        , confirm: call(confirm.cb)
    })

    // the race will wait for either the cancel or confirm callback to be invoked - which skirts
    // around the problem of trying to "put" from within a callback: don't put an event, instead
    // rely strictly on the resolution of a promise
    const race = yield race({
        cancel: call(cancel.promise)
        , confirm: call(confirm.promise)
    })

    ...

}
```

**Comment by slorber** [comment]
@aft-luke 

> A domain driven design approach would translate any event that is external to the component's domain into an internal representation, at which point the root of the reducer hierarchy becomes an aggregate root. This, unfortunately, means a very large reducer at the top of the hierarchy that must capture and translate every single event used by any component below.

Instead of doing this translation into reducers you should do it inside a saga. This is why I wanted something like redux-saga in the first place.

I don't think there is something close to an aggregate root in UIs because of the synchronous nature of interactions (while backend receive commands async). There's no need to validate commands because actually in the UI word everything has happened. You can notice this subtility because DOM events are always in the past tense, and the DOM does not send you commands that you can refuse. Even if there is a form error or whatever it's still an event, and the display of the error message has happened ;)

**Comment by aft-luke** [comment]
Thank you @slorber. Sorry for the very late response. I spent the last weeks with the Elm architecture and have been investigating CSP/core.async and the feasibility of clojurescript. Lots to think about on many different fronts.

> Instead of doing this translation into reducers you should do it inside a saga

This is the key. In order to keep modules decoupled, communication should be as limited as possible. If module A is interested in something about module B, it should setup a saga to listen for `B.SOME_EVENT`. A module's reducer(s) can then respond exclusively to that module's actions. Following this pattern is a great way to stay away from "action creep" where the api surface of a particular reducer has to handle events from all across the app.

**Comment by slorber** [comment]
@aft-luke we agree on that :)

you may be interested by this discussion: https://github.com/jarvisaoieong/redux-architecture/issues/1

**Comment by savethefails** [comment]
Sorry, a bit late to the party but running into something similar that I'm trying to wrap my head around.
Is it a good idea for a component to specify the actions that have taken place after an async call?

In this case, `FormContainer` gets its state from Redux Store and needs to know when an async call was successful in order to navigate away or show an error. Reducers know how to handle the success or error actions and update the state (not shown)


```javascript
function* callApi(){
  while(true) {
    const action = yield take(CALL_API)
    const {success, error} = fetch(action.url)
    if (success) {
       yield action.successActions.map( successAction => put(successAction, success.data) )
   }
   if (error) {
       yield action.errorActions.map( errorAction => put(errorAction, error.data) )
   }
}
```

```javascript
import {formSubmitted, formFailed} from './actions'

const mapStateToProps = (state) => {
 return {
  formStatus: state.form.status
 }
}

@connect(mapStateToProps)
class FormContainer extends Component {
 componentWillReceiveProps(nextProps){
    if (nextProps.formStatus.success) push('/success')
  }
 handleSubmit(){
   dispatch({
     type: CALL_API,
     successActions: [formSubmitted],
     successError: [formFailed],
   }
 } 

 render(){
   <Form onSubmit={handleSubmit} error={this.props.formStatus.error.message} /> 
 }
}
```

**Comment by slorber** [comment]
@savethefails not sure it's related to "put within a callback", but here's my opinion.

It looks like you want to navigate away from current page, after form save is successful. I guess your `push` is something like HistoryJS/ReactRouter push. Instead of letting your component do the push, which seems not their responsability, I would rather use a saga for that.


```javascript
function * redirectToSuccessPageAfterSuccessfulFormSubmit(){
  while(true) {
    const action = yield take(SUCCESS_FORM_SUBMIT)
   
    // Option1: 
    yield call(() => window.location.href = "/success");

    // Option2: HistoryJS
    yield call(() => history.push("/success"));

    // Option3: React-router-redux: 
    yield put(push('/foo'))

  }
}
```

Does it make sense?

**Comment by savethefails** [comment]
Thanks for the response @slorber!
Sorry if this veered off topic. This thread came up while trying to search for the answer and since I know your work thought I'd interject.

There are two things which I'm unsure about:
1. how many Sagas are too many? Every 'flow' through an app (in my case signing up, confirming signing up, signing in, signing out...) should they each get their own Saga? Should I dynamically mount Sagas when they're  needed for a specific flow? For example, Sign up is used once throughout the app, but the Saga would be there forever waiting to TAKE its action.
2. I think the code I presented is a bit too generic. My components get their state injected as props from the Redux store. Where a component's specific state can be found in the store dynamic and depends on lineage. This is also passed in by props (stateKey in the below example), so actions need the path in order to update a component.
```javascript
{  
 "components": {
  "SignUpController": {
   "state": {},
   "children": {
    "SignUpLayout": {
     "state": {},
      "children": {
       "SignUpFormContainer": {
        "state": {
         "email": "test@example.com"
        }
      }
     }
    }
   }
  }
 }
}
```
The issue is more like the below. Can a component dictate the story of a Saga when the specifics of how to respond to async actions can't be known by the Saga itself?

The example is therefore more like:
```javascript
import { componentStateChangedActionCreator } from './actions'

const mapStateToProps = (state, ownProps) => {
 const { stateKey } = ownProps  /* "Map/City/NorthWest/SnorgleTank15" */
 const componentState = stateKeyToComponentState(stateKey, state) 
 return componentState /* { "lat": "-44", "long": "-77" } */
}

@connect(mapStateToProps)
class SnorgleTank extends Component {
 handleClick(){
   const orderSucceeded = componentStateChangedActionCreator(
         this.props.stateKey,
         { snorgleBlaster: 'fire' }
      )
   const orderFailed = componentStateChangedActionCreator(
        this.props.stateKey,
        {retreatTo: 'basecamp'}
     )
   dispatch({
     type: FIRE_OR_RETREAT,
     current: { lat: this.props.lat, long: this.props.long },
     successActions: [orderSucceeded],
     errorActions: [orderFailed],
   }
 }
 render(){
  <button onClick={handleClick} />
 }
}
```

**Comment by slorber** [comment]
@savethefails 

> how many Sagas are too many?

I don't know if there are performance limits but sagas are just listeners so if they don't take it's not more costly than a connected component I guess. It is ok to not keep alive your sagas during the whole app process. For example if you build an onboarding saga, you can spawn it after signup, and cancel/end it at the end of the onboarding. A saga itself can track onboarding_start/cancel/end events to manage that onboarding saga. You likely don't want to congratulate the user everytime he creates a todo, but only during the TodoMVC onboarding.

> Can a component dictate the story of a Saga when the specifics of how to respond to async actions can't be known by the Saga itself?

I'm trying to understand your example but it's quite complicated so I'm unsure...

It looks to like you have components that can be arbitrarily nested and that you need to validate asynchronously the data that these components need to set somehow. For me it's fine to emit an event with a path to the state you want to update so that the saga can do the call and reuse that path in the reponse. You can even tell the saga which success/fail actions you want after async call, so that you have a very generic and reusable saga. 

However I think it's not good to emit actions creators inside your events so that the saga can call them. It reduces your boilerplate but it a bad idea for me. Are these actionCreators simples (I mean no thunks?). For me it would be better to do something like that:


```javascript
dispatch({
     type: CALL_API,
     current: { lat: this.props.lat, long: this.props.long },
     successActionTypes: ["ORDER_SUCCEEDED"],
     errorActionTypes: ["ORDER_FAILED"]
});

function* callApi(){
  while(true) {
    const action = yield take(CALL_API)
    const {success, error} = fetch(action.url)
    if (success) {
       yield action.successActionTypes.map(type => put({type: type, data: success.data}))
   }
   if (error) {
       yield action.errorActionTypes.map(type => put({type: type, data: error.data}))
   }
}
```

This won't work if you have complex actionCreators, but you can probably rework these existing action creators by using sagas as well.

**Comment by savethefails** [comment]
Perfect! I will look into cancelling Sagas and maybe even dynamically creating them for a specific flow. My action creators return only objects, but they should be run before being passed to the Saga action instead of being produced by the Saga action so that the log is serializable. Thank you very much!

**Comment by andreialecu** [comment]
I ran into the same issue with the following scenario:

```javascript
function* _subscribeFlow() {
  while (true) {
    var action = yield take('SUBSCRIBE');

    var fn = (x) => {
      if (x.id === action.eventId) {
        ... dispatch other action to refresh here...
      }
    };

    socket.on('x:changed', fn);

    action = yield take('UNSUBSCRIBE');
    socket.off('x:changed', fn);
  }
}
```

This uses socket.io, and I need to dispatch an action from the callback.

I could wrap the `socket.on` function in a promise but that seems wrong, because it can be called multiple times, and a promise is only supposed to resolve once.

 Any suggestions?

**Comment by andreialecu** [comment]
Alright, I came up with the following (with help of some stackoverflow answers):

```javascript
function createHandler(event) {
  let deferred;

  socket.on(event, e => {
    if (deferred) {
      deferred.resolve(e);
      deferred = null;
    }
  });

  return {
    nextMessage() {
      if (!deferred) {
        deferred = {
          promise: new Promise(resolve => deferred.resolve = resolve),
        };
      }

      return deferred.promise;
    },
  };
}

function* watchMessages(msgSource, filterId) {
  let message = yield call(msgSource.nextMessage);
  while (message) {
    if (message.id === filterId) {
      yield put({
        type: GET_ITEM,
        eventId: message.id,
      });
    }

    message = yield call(msgSource.nextMessage);
  }
}

function* _subscribeFlow() {
  var subscriptions = {};
  while (true) {
    var action = yield take('SUBSCRIBE');

    var msgSource = yield call(createHandler, 'x:changed');
    var task = yield fork(watchMessages, msgSource, action.eventId);

    action = yield take('UNSUBSCRIBE');
    task.cancel();
  }
}
```

Seems to work, but it's a lot of boilerplate.

**Comment by savethefails** [comment]
Hey @andreialecu, would this help?
 [*runSaga(iterator, {subscribe, dispatch, getState}, [monitor]*)](http://yelouafi.github.io/redux-saga/docs/api/index.html#runsagaiterator-subscribe-dispatch-getstate-monitor): ```Allows starting sagas outside the Redux middleware environment. Useful if you want to connect a Saga to external input/output, other than store actions.```

**Comment by mhoffmanniseki** [comment]
Hey @andreialecu and @savethefails ,
I had the same Issue. As runSage misses the connection to redux, which I also required an EventChannel does exactly what I need: http://yelouafi.github.io/redux-saga/docs/advanced/Channels.html

**Comment by savethefails** [comment]
@mhoffmanniseki Thanks! Can you explain what you mean by "misses the connection to redux"?

**Comment by mhoffmanniseki** [comment]
@savethefails By my opinion `runSaga(iterator, {subscribe, dispatch, getState}, [monitor])` is a way to use saga without redux. So it is an separat running instance without an connection to an redux instance. I've never tried this and my guessing is based on the documentation.

For me event channels are a clean solution to listen for async events. In my case I am using this to connect redux to firebase events.

**Comment by slorber** [comment]
@mhoffmanniseki yes you can run redux-saga without redux, as long as you an API so that take/put/select can work

See https://gist.github.com/slorber/c095671a14b2eccf8ad665a97a7b8ad1

**Comment by MrsBookik** [comment]
I still don't get it. I've read several issues and other texts about this topic... Mostly they solve complex problems and not a simple thing like mine. Can someone point me to a tutorial or something else that shows me how to pass a simple "yield put" within a callback? 

In my scenario i have to place a callback to receive the progress of a download-task and i want to put it into the redux-store with "yield put".

All i want to do is something like this:

```
function onDownloadFileProgress(data) {
  yield put({type: ACTIONS.S_PROGRESS, progress})
}
```


How to achieve that simple case? And why is it so difficult?

**Comment by Andarist** [comment]
Its 'difficult' because the callback needs to be run in generator/saga context.

Aint sure how would you like to use yours `onDownloadFileProgress`, please post an example usage and ill explain how you should approach it.

**Comment by MrsBookik** [comment]
Thx @Andarist  :) I'll give more context: 

I have a saga that downloads files from the internet using react-native-fs. There i have to pass a plain javascript function to receive the progress of current file download. 
And there we go (or not, because yield isnt working here and i need to do some fancy stuff):

```
function onProgress(progress) {
  yield put({type: ACTIONS.S_DOWNLOAD_PROGRESS, progress}) 
}

export function * loadMedia(id) {
  let url = `media/files/${id}`;

  const filename = RNFS.CachesDirectoryPath + '/' + id;

  const download = RNFS.downloadFile( {
    fromUrl: url,          
    toFile: filename,  
    background: false,
    progressDivider: 10,
    progress: onProgress,
  })

  yield download.promise;
}
```

**Comment by MrsBookik** [comment]
thx @Andarist, will provide more context/code:

```
function onProgress(progress) {
  // this isn't allowed here:
  yield put({type: ACTIONS.S_DOWNLOAD_PROGRESS, progress})
}

export function * loadFile(id) {
  let url = `media/${id}`;

  const tmpFilename = RNFS.CachesDirectoryPath + '/' + id;

  const download = RNFS.downloadFile( {
    fromUrl: url,          
    toFile:tmpFilename,  
    background: false,
    progressDivider: 5,
    progress: onProgress,
  })

  yield download.promise;
}
```

**Comment by Andarist** [comment]
Oh, yeah - its kinda cumbersome with generators in javascript, nothing really which could be simplified in the library itself.

I think the most idiomatic way to do this in saga is to use `eventChannel`. Its exactly for such uses cases - connecting external event sources (other than redux / redux-saga) through the channel to the redux-saga context.

More can be read in the docs - but basically you need to wrap your source (`RNFS.downloadFile` in your case) with `eventChannel`. And from there you can use `emit` argument to put things on the created `channel`. And from there you can easily just `take` and `put` events

**Comment by slorber** [comment]
If you just look for a simple workaround this certainly is not the way it's supposed to be done but it still works:

```javascript
function onProgress(progress) {
  store.dispatch({type: ACTIONS.S_DOWNLOAD_PROGRESS, progress})
}
```

You won't have the testability/analysis benefits of a yielded effect, but for this kind of usecase it may be fine

**Comment by benwiley4000** [comment]
@aft-luke your `bindCallbackToPromise` is a very slick temporary solution in my case. In the medium-to-long-term I expect we'll be able to eliminate the callback but our system uses a separate middleware which expects callbacks on certain actions. Appreciate the ingenuity. 😉

**Comment by niconistal** [comment]
Hey @MrsBookik did you find a solution? I'm trying to do the exact same thing.

**Comment by Andarist** [comment]
https://decembersoft.com/posts/file-upload-progress-with-redux-saga/

**Comment by SoundBlaster** [comment]
@Andarist thank you!

**Comment by dhruvdangi** [comment]
@Andarist Thanks!

**Comment by yardenapp** [comment]
I used an eventChannel to dispatch an action from a callback within the generator function
```
import {eventChannel} from 'redux-saga';
import {call, take} from 'redux-saga/effects';

function createEventChannel(setEmitter) {
    return eventChannel(emitter => {
        setEmitter(emitter)
        return () => {
          
        }
      }
    )
}

function* YourSaga(){
    let emitter;
    const internalEvents = yield call(createEventChannel, em => emitter = em)

    const scopedCallback = () => {
        emitter({type, payload})
    }

    while(true){
        const action = yield take(internalEvents)
        yield put(action)
    }
}
```

**Comment by euroclydon37** [comment]
Here's what I ended up doing. I was trying to send a datagram message using node.js. This is pretty straight forward to me, with only a _tiny_ extra work. I admittedly had to stop and google a bit at first, as the solution, though simple, isn't obvious.
```js
const createChannel = fn => eventChannel(fn);

function* sendMessage({ payload }) {
  if (!socket) {
    yield put({ type: SOCKET.SEND_FAILURE, payload: 'socket is undefined' });
  }

  const { address, port, msg } = payload;

  const resultChannel = yield call(createChannel, emitter => {
    socket.send(JSON.stringify(msg), port, address, err => {
      emitter({ error: err });
    });
  });

  const { error } = yield take(resultChannel);

  if (error) {
    yield put({ type: SOCKET.SEND_FAILURE, payload: error });
  }
}
```

**Comment by watch-janick** [comment]
> If you just look for a simple workaround this certainly is not the way it's supposed to be done but it still works:
> 
> ```js
> function onProgress(progress) {
>   store.dispatch({type: ACTIONS.S_DOWNLOAD_PROGRESS, progress})
> }
> ```
> 
> You won't have the testability/analysis benefits of a yielded effect, but for this kind of usecase it may be fine

How do you access `store` within a saga?

**Comment by gitowiec** [comment]
> If you just look for a simple workaround this certainly is not the way it's supposed to be done but it still works:
> 
> ```js
> function onProgress(progress) {
>   store.dispatch({type: ACTIONS.S_DOWNLOAD_PROGRESS, progress})
> }
> ```
> 
> You won't have the testability/analysis benefits of a yielded effect, but for this kind of usecase it may be fine

This is the approach I took. Because all advanced solutions mentioned in this thread are beyond my knowledge to apply them to my case (I want to dispatch/put action in the moment when modal shows up)
