### ISSUE TITLE
Cancelling "await" 

### ISSUE THREAD

**Issue by bradennapier** [yelouafi/redux-saga#83]
How would one go about cancelling an await that is used within redux sagas?

**Comment by slorber** [comment]
I don't think it is possible since that `await` is not processed by the redux-saga processor but by the browser so it does not generate a cancellable redux-saga task.

What is the usecase of using await inside redux-saga exactly? can't you just use yield ?

**Comment by yelouafi** [comment]
As @slorber  said, the `await` can be replaced by `yield` because the middleware automatically resolves yielded Promises. 

I'd recommand using `call` to invoke Promised functions as it can make testing your Sagas easier. For more infos see [Declarative Effects section](http://yelouafi.github.io/redux-saga/docs/basics/DeclarativeEffects.html)
